Repository apache/bookkeeper, pull requests merged in 2018-10, with the labels that each got.

#1720 [table service] Intercepted storage server channel should shutdown the underlying managed channel
  stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/channel/StorageServerChannel.java
  stream/clients/java/base/src/test/java/org/apache/bookkeeper/clients/impl/channel/TestStorageServerChannel.java
Labels: area/tableservice, release/4.9.0, type/bug

#1725 Add optional compile time only annotations-api dependency dropped in JDK11
  pom.xml
  stream/common/pom.xml
  stream/distributedlog/core/pom.xml
  stream/proto/pom.xml
  stream/tests-common/pom.xml
Labels: area/build, release/4.9.0, type/task

#1722 [table service][client] Provide a simple version of storage clients
  stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/SimpleClientBase.java
  stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/SimpleStorageClientImpl.java
  stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/StorageClientBuilder.java
  stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/admin/SimpleStorageAdminClientImpl.java
  stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/config/StorageClientSettings.java
  stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/container/StorageContainerClientInterceptor.java
  stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/utils/RetryUtils.java
  stream/clients/java/kv/src/main/java/org/apache/bookkeeper/clients/impl/kv/PByteBufSimpleTableImpl.java
  tests/integration/cluster/src/test/java/org/apache/bookkeeper/tests/integration/stream/StorageAdminClientTest.java
  tests/integration/cluster/src/test/java/org/apache/bookkeeper/tests/integration/stream/StreamClusterTestBase.java
  tests/integration/cluster/src/test/java/org/apache/bookkeeper/tests/integration/stream/TableClientTest.java
Labels: area/tableservice, release/4.9.0, type/feature

#1723 [table service][client] Implement the python client to access tables
  stream/clients/python/bookkeeper/admin/client.py
  stream/clients/python/bookkeeper/admin/namespace.py
  stream/clients/python/bookkeeper/admin/namespaces.py
  stream/clients/python/bookkeeper/common/constants.py
  stream/clients/python/bookkeeper/common/exceptions.py
  stream/clients/python/bookkeeper/common/future/polling.py
  stream/clients/python/bookkeeper/common/method.py
  stream/clients/python/bookkeeper/common/retry.py
  stream/clients/python/bookkeeper/common/timeout.py
  stream/clients/python/bookkeeper/kv/client.py
  stream/clients/python/bookkeeper/kv/table.py
  stream/clients/python/bookkeeper/proto/__init__.py
  stream/clients/python/examples/admin.py
  stream/proto/src/main/java/org/apache/bookkeeper/stream/protocol/ProtocolConstants.java
Labels: area/client, area/tableservice, release/4.9.0, type/feature

#1729 Decorate OrderedExecutor threads rather than runnables
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedScheduler.java
  bookkeeper-common/src/test/java/org/apache/bookkeeper/common/util/TestOrderedExecutorDecorators.java
Labels: area/bookie, area/client, release/4.9.0, type/improvement

#1727 [table services][perf] Provides a simple perf tool for testing put and inc performance
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/service/DLNamespaceProviderService.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
  tools/perf/pom.xml
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/BKPerf.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/TablePerfCommandGroup.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/BenchmarkCommand.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/BenchmarkTask.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/IncrementRandomTask.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/IncrementSequentialTask.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/IncrementTask.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/KeyGenerator.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/PerfClient.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/WriteRandomTask.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/WriteSequentialTask.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/WriteTask.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/package-info.java
Labels: area/tableservice, area/tools, release/4.9.0, type/task

#1683 Enhance Auditor
  .travis.yml
  bookkeeper-proto/src/main/proto/DataFormats.proto
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerUnderreplicationManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationStats.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/BookKeeperConstants.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorLedgerCheckerTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestLedgerUnderreplicationManager.java
Labels: area/autorecovery, release/4.9.0, type/improvement

#1716 Fix Kerberos tests on JDK11:
  bookkeeper-server/pom.xml
  bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/LedgerManagerIteratorTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/sasl/GSSAPIBookKeeperTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/sasl/MiniKdc.java
  pom.xml
Labels: area/tests, release/4.9.0, type/improvement

#1730 [table service][storage] improve the logic on creating the meta range for a table
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/StorageContainerStoreBuilder.java
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/metadata/MetaRangeStoreImpl.java
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/metadata/RootRangeStoreImpl.java
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/service/RangeStoreServiceFactoryImpl.java
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/service/RangeStoreServiceImpl.java
  stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/metadata/MetaRangeStoreImplTest.java
  stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/metadata/TestRootRangeStoreImpl.java
Labels: area/tableservice, release/4.9.0, type/improvement

#1732 Add Oracle JDK11 to Travis CI build
  .travis.yml
Labels: area/build, area/tests, release/4.9.0, type/improvement

#1731 [table service][stats] enable stats for grpc calls on both client and server
  bookkeeper-benchmark/pom.xml
  bookkeeper-common/src/test/java/org/apache/bookkeeper/test/TestStatsProvider.java
  metadata-drivers/etcd/pom.xml
  stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/config/StorageClientSettings.java
  stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/channel/StorageServerChannel.java
  stream/common/pom.xml
  stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/ClientStats.java
  stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/MonitoringClientCall.java
  stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/MonitoringClientCallListener.java
  stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/MonitoringClientInterceptor.java
  stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/MonitoringServerCall.java
  stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/MonitoringServerCallListener.java
  stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/MonitoringServerInterceptor.java
  stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/ServerStats.java
  stream/common/src/main/java/org/apache/bookkeeper/common/grpc/stats/package-info.java
  stream/common/src/test/java/org/apache/bookkeeper/common/grpc/stats/ClientStatsTest.java
  stream/common/src/test/java/org/apache/bookkeeper/common/grpc/stats/GrpcStatsIntegrationTest.java
  stream/common/src/test/java/org/apache/bookkeeper/common/grpc/stats/ServerStatsTest.java
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/grpc/GrpcServer.java
Labels: area/stats, area/tableservice, release/4.9.0, type/improvement

#1726 Introduce lifecycle components for managing components in AutoRecovery
  bookkeeper-server/pom.xml
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/Main.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/service/AutoRecoveryService.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieInitializationTest.java
Labels: area/autorecovery, release/4.9.0, type/improvement

#1734 [table service][client] provide scripts for uploading python clients to pypi
  pom.xml
  stream/clients/python/.gitignore
  stream/clients/python/README.md
  stream/clients/python/README.rst
  stream/clients/python/scripts/publish.sh
  stream/clients/python/scripts/publish_staging.sh
  stream/clients/python/setup.py
Labels: area/tableservice, release/4.9.0, type/task

#1741 Issue #1740: IOUtils.close() only accepts Closeable as a vararg which results in unnecessary Object[] created if only one Closeable passed there
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/IOUtils.java
Labels: area/bookie, release/4.9.0, type/improvement

#1739 Issue #1738: Journal: add a metric for the time ForceWriteRequest spent in the queue
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookKeeperServerStats.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
Labels: area/bookie, area/stats, release/4.9.0, type/improvement

#1735 Issue 1703: IllegalReferenceCountException at closing EntryLogManagerForSingleEntryLog
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java
Labels: area/bookie, release/4.7.3, release/4.8.1, release/4.9.0, type/bug

#1743 [build] Fix checkstyle issues on branch47
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ReadLastConfirmedAndEntryOp.java
Labels: area/build, release/4.7.3, type/bug

#1744 ISSUE #1737: EntryMemTable.newEntry: always make a copy
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryMemTable.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
Labels: area/bookie, release/4.7.3, release/4.8.1, release/4.9.0, type/bug

#1745 ISSUE #1737: EntryMemTable.newEntry: always make a copy
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryMemTable.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
Labels: area/bookie, release/4.8.1, type/bug

#1736 ReadEntryCallback in ReadLedgerEntriesCmd shouldn't release buffer.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
Labels: area/tools, release/4.8.1, release/4.9.0, type/bug

#1733 [table service][client] storage client can open tables on a different namespace
  stream/api/src/main/java/org/apache/bookkeeper/api/StorageClient.java
  stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/SimpleClientBase.java
  stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/SimpleStorageClientImpl.java
  stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/StorageClientBuilder.java
  stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/StorageClientImpl.java
  stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/admin/SimpleStorageAdminClientImpl.java
  stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/admin/StorageAdminClient.java
  stream/clients/java/all/src/main/java/org/apache/bookkeeper/clients/admin/StorageAdminClientImpl.java
  stream/clients/java/all/src/test/java/org/apache/bookkeeper/clients/StorageClientImplTest.java
  stream/clients/java/all/src/test/java/org/apache/bookkeeper/clients/admin/TestStorageAdminClientImpl.java
Labels: area/tableservice, release/4.9.0, type/improvement

#1747 Set ConnectionExpired Listener to MetadataClientDriver in AR
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MetadataClientDriver.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/zk/ZKMetadataClientDriver.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorElector.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/MetadataDriversTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AutoRecoveryMainTest.java
  metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdMetadataClientDriver.java
Labels: area/autorecovery, area/metadata, release/4.9.0, type/bug

#1749 [build] Fix build & bash script error when not using `stream` profile
  .travis.yml
  .travis_scripts/build.sh
  bin/bookkeeper
  pom.xml
  tools/pom.xml
Labels: area/build, release/4.9.0, type/bug

#1754 Netty allocator wrapper
  bookkeeper-common-allocator/pom.xml
  bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/ByteBufAllocatorBuilder.java
  bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/LeakDetectionPolicy.java
  bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/OutOfMemoryPolicy.java
  bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/PoolingPolicy.java
  bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/impl/ByteBufAllocatorBuilderImpl.java
  bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/impl/ByteBufAllocatorImpl.java
  bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/impl/package-info.java
  bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/package-info.java
  bookkeeper-common-allocator/src/test/java/org/apache/bookkeeper/common/allocator/impl/ByteBufAllocatorBuilderTest.java
  pom.xml
Labels: area/tools, release/4.9.0, type/improvement

#1753 Adding multi-node ZKCluster test util class
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieInitializationTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerStorageCheckpointTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/TestLongZkLedgerIdGenerator.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/TestZkLedgerIdGenerator.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestLedgerUnderreplicationManager.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ZooKeeperCluster.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ZooKeeperClusterUtil.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ZooKeeperUtil.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/TestZkUtils.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/zookeeper/TestZooKeeperClient.java
Labels: area/tests, release/4.9.0, type/task

#1751 Modules dependencies do not need to be included in checksum Jar
  circe-checksum/src/main/assembly/assembly.xml
Labels: area/build, release/4.9.0, type/improvement

#1646 Use immutable metadata in LedgerHandle
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/EnsembleUtils.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandleAdv.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadata.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadataBuilder.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ReadOnlyLedgerHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/api/WriteHandle.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ClientUtil.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/DeferredSyncTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/HandleFailuresTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerClose2Test.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MdcContextTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestDisableEnsembleChange.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestReadLastConfirmedLongPoll.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/MockLedgerManager.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ConditionalSetTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/TestUtils.java
Labels: area/client, release/4.9.0, type/improvement

#1759 Remove LedgerMetadata#getEnsembles in favour of #getAllEnsembles
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/ScanAndCompareGarbageCollector.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerChecker.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragment.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadata.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadataBuilder.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/UpdateLedgerOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/BookieLedgerIndexer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/TestGcOverreplicatedLedger.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieRecoveryTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieWriteLedgerTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/HandleFailuresTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerClose2Test.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerRecovery2Test.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestDelayEnsembleChange.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestDisableEnsembleChange.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestFencing.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestLedgerChecker.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestLedgerFragmentReplication.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestMaxEnsembleChangeNum.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestSequenceRead.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestSpeculativeRead.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/UpdateLedgerOpTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/api/BookKeeperBuildersTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicBookieCheckTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/BookieAutoRecoveryTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestAutoRecoveryAlongWithBookieServers.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
  stream/distributedlog/core/src/main/java/org/apache/bookkeeper/client/LedgerReader.java
  tests/backward-compat/recovery-no-password/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatRecoveryNoPassword.groovy
Labels: area/client, release/4.9.0, type/improvement

#1762 Don't cache Bookie hostname DNS resolution forever
  bookkeeper-server/src/main/java/org/apache/bookkeeper/net/BookieSocketAddress.java
Labels: area/client, release/4.9.0, type/bug, type/improvement

#1758 [merge script] remove authors section
  dev/bk-merge-pr.py
  dev/bk-merge-pr3.py
Labels: area/build, release/4.9.0, type/task

#1760 Kill LedgerMetadata#isConflictWith
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadata.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerMetadataTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/UpdateLedgerCmdTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/UpdateLedgerOpTest.java
Labels: area/client, release/4.9.0, type/improvement

#1764 [website] Fix broken link to ledger-api#example-application
  site/docs/4.7.2/api/ledger-api.md
  site/docs/4.8.0/api/ledger-api.md
  site/docs/latest/api/ledger-api.md
Labels: area/documentation, release/4.9.0, type/bug

#1766 Issue #1752: Etcd docker based tests are running on wrong jobs on CI
  .test-infra/jenkins/job_bookkeeper_precommit_integrationtests.groovy
  .test-infra/scripts/pre-docker-tests.sh
  metadata-drivers/etcd/pom.xml
Labels: area/tests, release/4.9.0, type/improvement

#1772 [tests] Fix integration test TestCompatUpgradeYahooCustom.testUpgradeYahooCustom
  bin/bookkeeper
Labels: area/bookie, area/tools, release/4.9.0, type/bug

#1771 [table service] Fix python client can't read keys written by java clients
  pom.xml
  stream/clients/python/bookkeeper/admin/client.py
  stream/clients/python/bookkeeper/admin/namespace.py
  stream/clients/python/bookkeeper/admin/namespaces.py
  stream/clients/python/bookkeeper/common/constants.py
  stream/clients/python/bookkeeper/common/exceptions.py
  stream/clients/python/bookkeeper/kv/client.py
  stream/clients/python/bookkeeper/kv/table.py
  stream/clients/python/nox.py
  stream/clients/python/noxfile.py
  stream/clients/python/scripts/docker_build.sh
  stream/clients/python/scripts/docker_integration_tests.sh
  stream/clients/python/scripts/run_integration_tests.sh
  stream/clients/python/setup.py
  stream/clients/python/tests/integration/bookkeeper/__init__.py
  stream/clients/python/tests/integration/bookkeeper/admin/test_admin_client.py
  stream/clients/python/tests/integration/bookkeeper/kv/test_client.py
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/sc/StorageContainerImpl.java
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/service/RangeStoreServiceImpl.java
  tests/docker-images/current-version-image/Dockerfile
  tests/docker-images/current-version-image/pom.xml
  tests/docker-images/current-version-image/scripts/install-python-client.sh
Labels: area/tableservice, release/4.9.0, type/bug

#1776 Reduce stack traces in logs for common cases
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
Labels: area/logging, release/4.9.0, type/improvement

#1774 ISSUE #1757: prevent race between flush and delete from recreating index
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileInfo.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileInfoBackingCache.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexInMemPageMgr.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexPersistenceMgr.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerEntryPage.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerCacheTest.java
Labels: area/bookie, release/4.7.1, release/4.7.3, type/bug

#1775 ISSUE #1757: prevent race between flush and delete from recreating index
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileInfo.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileInfoBackingCache.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexInMemPageMgr.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexPersistenceMgr.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerEntryPage.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerCacheTest.java
Labels: area/bookie, release/4.8.1, type/bug
