Repository apache/bookkeeper, pull requests merged in 2019-08, with the labels that each got.

#2139 Replace C style array declaration with Java style
  bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchThroughputLatency.java
  bookkeeper-benchmark/src/test/java/org/apache/bookkeeper/benchmark/TestBenchmark.java
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Cookie.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexPersistenceMgr.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDescriptor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDescriptorImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerDescriptorReadOnlyImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/ArrayGroupSort.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeper.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/FlatLedgerManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerLayout.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerMetadataSerDe.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerIdGenerator.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/net/DNS.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClientImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/sasl/SaslServerState.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/DecommissionService.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/ListBookieInfoService.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/RecoveryBookieService.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/InfoCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/RecoverCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/AvailabilityOfEntriesOfLedger.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ZeroBuffer.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerStorageCheckpointTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeper.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestFencing.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestPendingReadLacOp.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestReadLastEntry.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/LedgerManagerIteratorTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieClientTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieReadWriteTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieZKExpireTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ConcurrentLedgerTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/OpStatTest.java
  bookkeeper-stats-providers/codahale-metrics-provider/src/test/java/org/apache/bookkeeper/stats/codahale/FastTimerTest.java
  buildtools/src/main/resources/bookkeeper/checkstyle.xml
  circe-checksum/src/main/java/com/scurrilous/circe/crc/Sse42Crc32C.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/federated/FederatedZKLogMetadataStore.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/tools/Tool.java
Labels: area/bookie, area/client, release/4.10.0, type/cleanup

#2141 Replicascheck comprehensive testcases.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/AvailabilityOfEntriesOfLedger.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTest.java
Labels: area/autorecovery, area/tests, release/4.10.0, type/improvement

#2137 Simplify if statements
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/annotation/InterfaceAudience.java
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/annotation/InterfaceStability.java
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/conf/validators/RangeValidator.java
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedScheduler.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/auth/BookKeeperPrincipal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileSystemUpgrade.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/api/LedgerMetadata.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/MSLedgerManagerFactory.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/net/NetworkTopologyImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/streaming/LedgerOutputStream.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/LedgerCommand.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/auth/TestAuth.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieDeferredSyncTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerCacheTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MetadataUpdateLoopTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/RoundRobinDistributionScheduleTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/BKDistributedLogManager.java
  stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/DLSN.java
Labels: area/build, release/4.10.0, type/improvement

#2154 [bookie] auto refresh tls cert at bookie-server
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/FileModifiedTimeUpdater.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/TLSContextFactory.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
  conf/bk_server.conf
Labels: area/security, release/4.10.0, type/feature
