Repository apache/bookkeeper, pull requests merged in 2020-07, with the labels that each got.

#2370 Bump Python client version: 4.12.0-alpha-0
  stream/clients/python/setup.py
Labels: area/build, release/4.12.0, type/task

#2367 Add slack-digest script which generates per channel digest emails to …
  .test-infra/scripts/slack-email-digest/.gitignore
  .test-infra/scripts/slack-email-digest/README.md
  .test-infra/scripts/slack-email-digest/configuration-example.yaml
  .test-infra/scripts/slack-email-digest/requirements.txt
  .test-infra/scripts/slack-email-digest/slack_email_digest.py
Labels: area/build, release/4.12.0, type/improvement

#2372 [bookkeeper-site] fix latest version of bookkeeper website
  site/_config.yml
Labels: area/website, release/4.12.0, type/bug

#2373 Issue 2264: Bookie cannot perform Garbage Collection in case of corrupted EntryLogger file
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
Labels: area/autorecovery, area/bookie, release/4.10.1, release/4.11.1, release/4.12.0, type/bug

#2344 [SITE] Improve the user experience of the site
  site/_sass/vendor/bulma/sass/layout/footer.sass
  site/css/style.sass
Labels: area/website, release/4.12.0, type/improvement

#2383 fix fillReadAheadCache stat bug
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
Labels: area/bookie, release/4.12.0, type/bug
