Repository apache/bookkeeper, pull requests merged in 2020-01, with the labels that each got.

#2228 Account Apache Thrift and Http Client files in LICENSE files - Fix build on Travis
  .travis.yml
  .travis_scripts/build.sh
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
Labels: area/build, release/4.11.0, type/task

#2232 Remove Twitter libraries:
  bin/common.sh
  bookkeeper-dist/all/pom.xml
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  bookkeeper-dist/src/main/resources/deps/netty-3.10.1.Final/LICENSE.base64.txt
  bookkeeper-dist/src/main/resources/deps/netty-3.10.1.Final/LICENSE.jsr166y.txt
  bookkeeper-dist/src/main/resources/deps/netty-3.10.1.Final/LICENSE.jzlib.txt
  bookkeeper-dist/src/main/resources/deps/netty-3.10.1.Final/LICENSE.webbit.txt
  bookkeeper-dist/src/main/resources/deps/paranamer-2.8/LICENSE.txt
  bookkeeper-dist/src/main/resources/deps/scala-library-2.11.7/LICENSE.md
  bookkeeper-dist/src/main/resources/deps/scala-parser-combinators_2.11-1.0.4/LICENSE.md
  bookkeeper-dist/src/main/resources/deps/scala-reflect-2.11.8/LICENSE.md
  bookkeeper-http/pom.xml
  bookkeeper-http/twitter-http-server/pom.xml
  bookkeeper-http/twitter-http-server/src/main/java/org/apache/bookkeeper/http/twitter/TwitterAbstractHandler.java
  bookkeeper-http/twitter-http-server/src/main/java/org/apache/bookkeeper/http/twitter/TwitterHttpHandlerFactory.java
  bookkeeper-http/twitter-http-server/src/main/java/org/apache/bookkeeper/http/twitter/TwitterHttpServer.java
  bookkeeper-http/twitter-http-server/src/main/java/org/apache/bookkeeper/http/twitter/package-info.java
  bookkeeper-http/twitter-http-server/src/test/java/org/apache/bookkeeper/http/twitter/TestTwitterHttpServer.java
  bookkeeper-server/pom.xml
  bookkeeper-stats-providers/pom.xml
  bookkeeper-stats-providers/twitter-finagle-provider/pom.xml
  bookkeeper-stats-providers/twitter-finagle-provider/src/main/java/org/apache/bookkeeper/stats/twitter/finagle/CounterImpl.java
  bookkeeper-stats-providers/twitter-finagle-provider/src/main/java/org/apache/bookkeeper/stats/twitter/finagle/FinagleStatsLoggerImpl.java
  bookkeeper-stats-providers/twitter-finagle-provider/src/main/java/org/apache/bookkeeper/stats/twitter/finagle/FinagleStatsProvider.java
  bookkeeper-stats-providers/twitter-finagle-provider/src/main/java/org/apache/bookkeeper/stats/twitter/finagle/OpStatsLoggerImpl.java
  bookkeeper-stats-providers/twitter-finagle-provider/src/main/java/org/apache/bookkeeper/stats/twitter/finagle/package-info.java
  bookkeeper-stats-providers/twitter-ostrich-provider/pom.xml
  bookkeeper-stats-providers/twitter-ostrich-provider/src/main/java/org/apache/bookkeeper/stats/twitter/ostrich/CounterImpl.java
  bookkeeper-stats-providers/twitter-ostrich-provider/src/main/java/org/apache/bookkeeper/stats/twitter/ostrich/OpStatsLoggerImpl.java
  bookkeeper-stats-providers/twitter-ostrich-provider/src/main/java/org/apache/bookkeeper/stats/twitter/ostrich/OstrichProvider.java
  bookkeeper-stats-providers/twitter-ostrich-provider/src/main/java/org/apache/bookkeeper/stats/twitter/ostrich/OstrichStatsLoggerImpl.java
  bookkeeper-stats-providers/twitter-ostrich-provider/src/main/java/org/apache/bookkeeper/stats/twitter/ostrich/package-info.java
  bookkeeper-stats-providers/twitter-science-provider/pom.xml
  bookkeeper-stats-providers/twitter-science-provider/src/main/java/org/apache/bookkeeper/stats/twitter/science/CounterImpl.java
  bookkeeper-stats-providers/twitter-science-provider/src/main/java/org/apache/bookkeeper/stats/twitter/science/HTTPStatsExporter.java
  bookkeeper-stats-providers/twitter-science-provider/src/main/java/org/apache/bookkeeper/stats/twitter/science/OpStatsLoggerImpl.java
  bookkeeper-stats-providers/twitter-science-provider/src/main/java/org/apache/bookkeeper/stats/twitter/science/TwitterStatsLoggerImpl.java
  bookkeeper-stats-providers/twitter-science-provider/src/main/java/org/apache/bookkeeper/stats/twitter/science/TwitterStatsProvider.java
  bookkeeper-stats-providers/twitter-science-provider/src/main/java/org/apache/bookkeeper/stats/twitter/science/package-info.java
  conf/bk_server.conf
  dev/release/001-release-branch.sh
  dev/release/002-release-prepare.sh
  dev/release/003-release-perform.sh
  pom.xml
  site/docs/latest/admin/metrics.md
  stats/utils/src/main/java/org/apache/bookkeeper/stats/utils/StatsDocGenerator.java
Labels: area/bookie, release/4.11.0, type/cleanup

#2226 ISSUE-2224: Config ServerConfiguration with setAllowLoopback(true) for Unit Tests
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/GarbageCollectorThreadTest.java
Labels: area/config, release/4.11.0, type/bug

#2235 [bookie-server] add support of client auto cert refresh
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/TLSContextFactory.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
Labels: area/client, release/4.11.0, type/feature

#2238 Increase the 'segment store path' in the 'Initializing stream cluster' log
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/cluster/ZkClusterInitializer.java
Labels: area/tools, release/4.11.0, type/improvement

#2237 Create ledgersRootPath recursively for 'bin/bookkeeper shell metaformat'
  bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/ZKRegistrationManager.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/discover/TestZkRegistrationManager.java
Labels: area/tools, release/4.11.0, type/improvement

#2248 [hotfix] fix the http endpoint component count error
  site/docs/4.10.0/admin/http.md
  site/docs/4.6.0/admin/http.md
  site/docs/4.6.1/admin/http.md
  site/docs/4.6.2/admin/http.md
  site/docs/4.7.0/admin/http.md
  site/docs/4.7.1/admin/http.md
  site/docs/4.7.2/admin/http.md
  site/docs/4.7.3/admin/http.md
  site/docs/4.8.0/admin/http.md
  site/docs/4.8.1/admin/http.md
  site/docs/4.8.2/admin/http.md
  site/docs/4.9.0/admin/http.md
  site/docs/4.9.1/admin/http.md
  site/docs/4.9.2/admin/http.md
  site/docs/latest/admin/http.md
Labels: area/documentation, release/4.11.0, type/bug

#2249 [hotfix][docs] remove redundant word in protocol documents
  site/docs/4.10.0/development/protocol.md
  site/docs/4.5.0/development/protocol.md
  site/docs/4.5.1/development/protocol.md
  site/docs/4.6.0/development/protocol.md
  site/docs/4.6.1/development/protocol.md
  site/docs/4.6.2/development/protocol.md
  site/docs/4.7.0/development/protocol.md
  site/docs/4.7.1/development/protocol.md
  site/docs/4.7.2/development/protocol.md
  site/docs/4.7.3/development/protocol.md
  site/docs/4.8.0/development/protocol.md
  site/docs/4.8.1/development/protocol.md
  site/docs/4.8.2/development/protocol.md
  site/docs/4.9.0/development/protocol.md
  site/docs/4.9.1/development/protocol.md
  site/docs/4.9.2/development/protocol.md
  site/docs/latest/development/protocol.md
Labels: area/documentation, release/4.11.0, type/bug

#2250 [hotfix][docs] fix error in leger api document
  site/docs/4.10.0/api/ledger-api.md
  site/docs/4.5.0/api/ledger-api.md
  site/docs/4.5.1/api/ledger-api.md
  site/docs/4.6.0/api/ledger-api.md
  site/docs/4.6.1/api/ledger-api.md
  site/docs/4.6.2/api/ledger-api.md
  site/docs/4.7.0/api/ledger-api.md
  site/docs/4.7.1/api/ledger-api.md
  site/docs/4.7.2/api/ledger-api.md
  site/docs/4.7.3/api/ledger-api.md
  site/docs/4.8.0/api/ledger-api.md
  site/docs/4.8.1/api/ledger-api.md
  site/docs/4.8.2/api/ledger-api.md
  site/docs/4.9.0/api/ledger-api.md
  site/docs/4.9.1/api/ledger-api.md
  site/docs/4.9.2/api/ledger-api.md
  site/docs/latest/api/ledger-api.md
Labels: area/documentation, release/4.11.0, type/bug

#2251 Website: Update Release Management for new Time Based Release Plan
  site/community/releases.md
Labels: area/documentation, release/4.11.0, type/proposal

#2246 [CI] Migrate the Jenkins CI to Github Action
  .github/workflows/bookie-tests.yml
  .github/workflows/client-tests.yml
  .github/workflows/compatibility-check-java11.yml
  .github/workflows/compatibility-check-java8.yml
  .github/workflows/integration-tests.yml
  .github/workflows/pr-validation.yml
  .github/workflows/remaining-tests.yml
  .github/workflows/replication-tests.yml
  .github/workflows/tls-tests.yml
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/EntryMemTableTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/FileInfoBackingCacheTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/GcOverreplicatedLedgerTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerDirsManagerTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/SkipListArenaTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/SyncThreadTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/TestEntryLog.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/TestInterleavedLedgerStorage.java
Labels: area/build, release/4.11.0, type/improvement

#2211 bin/bookkeeper shell supports the -conf
  bin/bookkeeper
Labels: area/tools, release/4.11.0, type/improvement

#2253 Website: add EOL tag to navbar
  site/_config.yml
  site/_includes/navbar.html
Labels: area/website, release/4.11.0, type/improvement

#2256 Website: update Gemfile dependencies
  site/Gemfile
  site/Gemfile.lock
  site/Makefile
Labels: area/website, release/4.11.0, type/task

#2258 [code-style] fix build failure for check-style
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/cluster/ZkClusterInitializer.java
Labels: area/build, release/4.11.0, type/task
