Repository apache/bookkeeper, pull requests merged in 2020-12, with the labels that each got.

#2501 ISSUE #2451: Add sidebar to the documentation page
  site2/docs/getting-started.md
  site2/website/pages/en/index.js
  site2/website/sidebars.json
Labels: area/website, release/4.13.0, type/improvement

#2503 Upgrade ZooKeeper to 3.6.2
  bookkeeper-benchmark/pom.xml
  bookkeeper-dist/all/pom.xml
  bookkeeper-dist/server/pom.xml
  bookkeeper-server/pom.xml
  pom.xml
  stream/bk-grpc-name-resolver/pom.xml
  stream/distributedlog/core/pom.xml
  stream/distributedlog/io/dlfs/pom.xml
  tests/integration-tests-utils/pom.xml
Labels: area/build, release/4.13.0, type/improvement

#2496 Start HTTP Server in Bookie Standlone Mode
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/service/HttpService.java
  conf/standalone.conf
  stream/server/pom.xml
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/StorageServer.java
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/service/BookieService.java
Labels: area/bookie, release/4.13.0, type/improvement

#2498 getBookieInfo is stuck if no bookie is up
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookieInfoReader.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestGetBookieInfoTimeout.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
Labels: area/client, release/4.13.0, type/bug

#2502 [docs] Update dbStorage_writeCacheMaxSizeMb configuration description
  conf/bk_server.conf
  site/_data/config/bk_server.yaml
Labels: area/documentation, release/4.13.0, type/bug

#2507 Add Some Clarifications to the AutoRecovery Documentation
  site/docs/4.12.0/admin/autorecovery.md
Labels: area/documentation, release/4.13.0, type/improvement

#2469 java.lang.NullPointerException with metadataServiceUri = zk:///ledger…
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/zk/ZKMetadataDriverBase.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/WhoIsAuditorCommand.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieInitializationTest.java
Labels: area/metadata, release/4.13.0, type/bug

#2517 BookKeeper Standalone does not work after ZK upgrade - missing third party deps
  stream/server/pom.xml
Labels: area/metadata, release/4.13.0, type/bug

#2519 Allow DNSToSwitchMapping to access BookieAddressResolver
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeper.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/TopologyAwareEnsemblePlacementPolicy.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ZoneawareEnsemblePlacementPolicyImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/net/AbstractDNSToSwitchMapping.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/net/DNSToSwitchMapping.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/StaticDNSResolver.java
Labels: area/client, release/4.12.1, release/4.13.0, type/feature

#2515 Upgrade libraries Common Compress and Hadoop (only tests) to fix vulnerabilities
  pom.xml
Labels: area/tests, release/4.13.0, type/improvement

#2525 Activate GitHub Actions on all PRs and on push
  .github/workflows/bookie-tests.yml
  .github/workflows/client-tests.yml
  .github/workflows/compatibility-check-java11.yml
  .github/workflows/compatibility-check-java8.yml
  .github/workflows/integration-tests.yml
  .github/workflows/pr-validation.yml
  .github/workflows/remaining-tests.yml
  .github/workflows/replication-tests.yml
  .github/workflows/tls-tests.yml
Labels: area/build, release/4.13.0, type/infra

#2523 Issue 2522: Update jcommander from 1.48 to 1.78
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  pom.xml
  tools/framework/src/main/java/org/apache/bookkeeper/tools/framework/Cli.java
  tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/CreateCookieCommandTest.java
  tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/GenerateCookieCommandTest.java
  tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/cookie/UpdateCookieCommandTest.java
Labels: area/build, release/4.13.0, type/infra
