Repository apache/bookkeeper, pull requests merged in 2020-04, with the labels that each got.

#2231 Fix batch read data in cache does not take effect
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
Labels: area/bookie, release/4.11.0, type/bug

#2317 Force to use Python grpcio less then 1.26.0
  stream/clients/python/setup.py
Labels: area/build, release/4.11.0, type/bug

#2315 Issue 2274: The 'metaformat' command does not delete 'idgen' znode
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerFactory.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperAdminTest.java
Labels: area/tools, release/4.11.0, type/bug

#2278 Add forkCount option to parallelize build and tests
  pom.xml
Labels: area/build, release/4.11.0, type/task

#2271 Fix mistakes in documentation
  site/docs/4.10.0/development/protocol.md
  site/docs/4.10.0/getting-started/concepts.md
Labels: area/documentation, release/4.11.0, type/bug
