Repository apache/bookkeeper, pull requests merged in 2020-02, with the labels that each got.

#2259 Remove travis
  .travis.yml
  .travis_scripts/before_install.sh
  .travis_scripts/build.sh
Labels: area/build, release/4.11.0, type/task

#2214 BP-38 Publish Bookie Service Info on Metadata Service
  site/bps/BP-38-bookie-endpoint-discovery.md
Labels: area/website, release/4.11.0, type/proposal

#2265 Revert "bin/bookkeeper shell supports the -conf"
  bin/bookkeeper
Labels: area/client, release/4.11.0, type/bug

#2266 Fix method order in order to make the execution of TestEntryLog predictable
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/TestEntryLog.java
Labels: area/tests, release/4.11.0, type/task

#2254 Issue 2218: Write customMetadata on ledgers created by DistributedLog
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/BKAbstractLogWriter.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/BKDistributedLogManager.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/BookKeeperClient.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/api/DistributedLogManager.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/bk/LedgerMetadata.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/bk/SimpleLedgerAllocator.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/logsegment/BKLogSegmentEntryStore.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/logsegment/LogSegmentEntryStore.java
  stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestBKDistributedLogManager.java
  stream/distributedlog/core/src/test/java/org/apache/distributedlog/bk/TestLedgerAllocator.java
Labels: area/client, area/dlog, release/4.11.0, type/improvement
