Repository apache/bookkeeper, pull requests merged in 2021-11, with the labels that each got.

#2855 Issue #2854: Use correct lockpath, store Lock to heldLocks at ZkLedgerUnderreplicationManager#acquireUnderreplicatedLedger
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/GcOverreplicatedLedgerTest.java
Labels: type/bug

#2864 Release note for 4.14.3
  site/_config.yml
  site/docs/4.14.3/admin/autorecovery.md
  site/docs/4.14.3/admin/bookies.md
  site/docs/4.14.3/admin/decomission.md
  site/docs/4.14.3/admin/geo-replication.md
  site/docs/4.14.3/admin/http.md
  site/docs/4.14.3/admin/metrics.md
  site/docs/4.14.3/admin/perf.md
  site/docs/4.14.3/admin/placement.md
  site/docs/4.14.3/admin/upgrade.md
  site/docs/4.14.3/api/distributedlog-api.md
  site/docs/4.14.3/api/ledger-adv-api.md
  site/docs/4.14.3/api/ledger-api.md
  site/docs/4.14.3/api/overview.md
  site/docs/4.14.3/deployment/dcos.md
  site/docs/4.14.3/deployment/kubernetes.md
  site/docs/4.14.3/deployment/manual.md
  site/docs/4.14.3/development/codebase.md
  site/docs/4.14.3/development/protocol.md
  site/docs/4.14.3/getting-started/concepts.md
  site/docs/4.14.3/getting-started/installation.md
  site/docs/4.14.3/getting-started/run-locally.md
  site/docs/4.14.3/overview/overview.md
  site/docs/4.14.3/overview/releaseNotes.md
  site/docs/4.14.3/overview/releaseNotesTemplate.md
  site/docs/4.14.3/reference/cli.md
  site/docs/4.14.3/reference/config.md
  site/docs/4.14.3/reference/metrics.md
  site/docs/4.14.3/security/overview.md
  site/docs/4.14.3/security/sasl.md
  site/docs/4.14.3/security/tls.md
  site/docs/4.14.3/security/zookeeper.md
  site/releases.md
Labels: area/release, release/4.14.3

#2865 BP-44: Journal metrics enhancement
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookKeeperServerStats.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/stats/BookieStats.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/stats/JournalStats.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/OpStatTest.java
Labels: area/stats

#2861 BP-44: OrderedExecutor metrics
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedScheduler.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
Labels: area/stats

#2880 BP-44: Removed bookie port number from OrderedExecutor name
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
Labels: area/stats
