Repository apache/bookkeeper, pull requests merged in 2021-01, with the labels that each got.

#2532 2531: Fix noisy stacktrace at boot
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultBookieAddressResolver.java
Labels: area/client, area/logging, release/4.12.2, release/4.13.0

#2542 Check np for LifecycleComponent close
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/service/GrpcService.java
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/service/RegistrationStateService.java
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/service/StorageService.java
Labels: area/bookie, release/4.13.0, type/cleanup

#2543 Allow to configure Prometheus HTTP Server bind address
  bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java
  bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/TestPrometheusMetricsProvider.java
  conf/bk_server.conf
  site/_data/config/bk_server.yaml
Labels: area/http, area/stats, release/4.13.0, type/improvement

#2533 fix default value in bk_server.conf, sync with code default value
  conf/bk_server.conf
  site/_data/config/bk_server.yaml
Labels: area/config, release/4.13.0, type/cleanup

#2516 Sync 4.12.0 autorecovery doc to lastest
  site/docs/latest/admin/autorecovery.md
Labels: area/documentation, release/4.13.0, type/improvement

#2538 Fix BookKeeper shell "list bookies" in case of downbookie and reduce noisy log during re-replication in case of down bookie
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultBookieAddressResolver.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/helpers/CommandHelpers.java
Labels: area/client, release/4.12.2, release/4.13.0, type/bug

#2558 Issue 2557: Bookkeeper docker image build fails because of deprecated Python version for pip
  docker/Dockerfile
  tests/docker-images/current-version-image/Dockerfile
Labels: area/build, release/4.13.0, type/bug

#2554 Fixed failing tests for /stream.
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
Labels: area/tests, release/4.13.0, type/bug

#2560 Allow stream storage to use hostname instead of IP address
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/StorageServer.java
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/StreamStorageLifecycleComponent.java
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/conf/StorageServerConfiguration.java
Labels: area/tableservice, release/4.13.0, type/feature

#2555 Fixed: DLCheckpointStore rethrows exceptions as FNFE but swallows the rootcause
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/dlog/DLCheckpointStore.java
Labels: area/tableservice, release/4.13.0, type/improvement

#2564 Issue 2563: Fix SST file corruption.
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/dlog/DLOutputStream.java
Labels: area/tableservice, release/4.13.0, type/bug
