Repository apache/bookkeeper, pull requests merged in 2021-06, with the labels that each got.

#2739 [statestore] Cleanup local storage for statestore storage container
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/api/StateStoreSpec.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
  stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestRocksdbKVStoreCheckpoint.java
  stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestStateStore.java
  stream/storage/api/src/main/java/org/apache/bookkeeper/stream/storage/conf/StorageConfiguration.java
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/store/MVCCStoreFactoryImpl.java
Labels: area/dlog, release/4.15.0, type/improvement

#2744 Fix the typo in Auditor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
Labels: area/bookie, release/4.15.0, type/cleanup

#2743 Print usage in autorecovery command if needed
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
Labels: area/autorecovery, release/4.15.0, type/improvement

#2735 [Security] Exclude grpc-okhttp dependency
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  metadata-drivers/etcd/pom.xml
  stream/common/pom.xml
  stream/tests-common/pom.xml
Labels: area/security, release/4.15.0

#2720 Add the `tlsCertificatePath` to the configuration file
  conf/bk_server.conf
  site/_data/config/bk_server.yaml
Labels: area/config, area/documentation

#2708 BookKeeper-Client config to write ledger metadata with configured version
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerCreateOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadataBuilder.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieWriteLedgerTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeperTestCase.java
Labels: area/client, release/4.15.0

#2693 [Security] Upgrade vertx to 3.9.8, addresses CVE-2018-12541
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-http/vertx-http-server/src/main/java/org/apache/bookkeeper/http/vertx/VertxHttpServer.java
  pom.xml
Labels: area/security, release/4.15.0

#2734 [Build/Security] Upgrade Freebuilder version and fix the dependency
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  dependencies.gradle
  pom.xml
  stream/clients/java/base/build.gradle
Labels: area/security, release/4.15.0, type/improvement
