Repository apache/bookkeeper, pull requests merged in 2021-10, with the labels that each got.

#2808 set response body for bookie is_ready api
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieIsReadyService.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
Labels: type/improvement, area/http, release/4.15.0

#2801 Issue 2787: TestPerChannelBookieClient.testEpollChannelTcpUserTimeout fails
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/TestPerChannelBookieClient.java
Labels: area/tests

#2802 Add auditor get ledger throttle to avoid auto recovery zk session expire
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
  conf/bk_server.conf
Labels: area/metadata, area/autorecovery
