Repository apache/bookkeeper, pull requests merged in 2021-07, with the labels that each got.

#2740 Fix Bouncy Castle fips incompatible issue
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/TLSContextFactory.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
  tests/backward-compat/bc-non-fips/pom.xml
  tests/backward-compat/bc-non-fips/src/test/java/org/apache/bookkeeper/tls/TestBCNonFips.java
  tests/backward-compat/pom.xml
Labels: release/4.14.2

#2727 ISSUE #2726 Fix JAVA_HOME containing spaces
  bin/bkctl
  bin/bookkeeper
  bin/dlog
  stream/bin/streamstorage
  stream/bin/streamstorage-cli
Labels: area/utils, release/4.15.0, type/cleanup

#2751 [doc] Fix typo in bookkeeper config `tslProvider`
  site/_data/config/bk_server.yaml
Labels: area/website
