Repository apache/bookkeeper, pull requests merged in 2021-03, with the labels that each got.

#2631 Make Bookkeeper FIPS compliant by default
  bin/bookkeeper
  bookkeeper-dist/src/assemble/bin-all.xml
  bookkeeper-dist/src/assemble/bin-server.xml
  bookkeeper-dist/src/assemble/bkctl.xml
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/deps/bouncycastle-1.0.2/LICENSE.html
  bookkeeper-server/pom.xml
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tls/TLSContextFactory.java
  metadata-drivers/etcd/pom.xml
  pom.xml
  stream/common/pom.xml
  stream/tests-common/pom.xml
Labels: area/bookie, release/4.14.0, type/bug

#2632 Fix NetworkTopologyImpl#getLeaves returning set with null value in case of non existing scope
  bookkeeper-server/src/main/java/org/apache/bookkeeper/net/NetworkTopologyImpl.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/net/NetworkTopologyImplTest.java
Labels: area/client, release/4.12.2, release/4.13.1, release/4.14.0, type/bug

#2639 BP-43: Gradle migration
  site/bps/BP-43-gradle-migration.md
  site/community/bookkeeper_proposals.md
Labels: type/proposal

#2627 Allow DBLedgerStorage to force GC by disk listener
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageTest.java
Labels: area/bookie

#2626 Allow force compact entry log when disabling entry log compaction
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CompactionTest.java
  conf/bk_server.conf
Labels: area/bookie, release/4.14.0, type/bug

#2635 Handle corrupted checkpoints
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/journal/AbstractStateStoreWithJournal.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/CheckpointInfo.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksCheckpointer.java
  stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestRocksdbKVAsyncStoreWithCheckpoints.java
  stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestRocksdbKVStoreCheckpoint.java
  stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestStateStore.java
  stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksCheckpointerTest.java
Labels: area/tableservice, release/4.14.0, type/bug

#2616 Add fencing to recovery reads to avoid data loss issue
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerRecovery2Test.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockClientContext.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockBookieClient.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockBookies.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockLedgerData.java
Labels: area/client, release/4.14.0, type/bug

#2651 Fixed get-pip URL in Dockerfile
  docker/Dockerfile
  tests/docker-images/current-version-image/Dockerfile
Labels: area/build

#2643 adjust default rocksDbBlockCache size to 10%/numberOfLedgers of direct memory
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
  conf/bk_server.conf
Labels: area/bookie, type/improvement

#2641 Add checksum validation for SST files
  stream/proto/src/main/proto/kv_store.proto
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/StorageServer.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/api/StateStoreSpec.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/RocksUtils.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/CheckpointFile.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/CheckpointInfo.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksCheckpointer.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksdbCheckpointTask.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksdbRestoreTask.java
  stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestRocksdbKVAsyncStoreWithCheckpoints.java
  stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/kv/TestStateStore.java
  stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksCheckpointerTest.java
  stream/storage/api/src/main/java/org/apache/bookkeeper/stream/storage/conf/StorageConfiguration.java
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/store/MVCCStoreFactoryImpl.java
  stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/store/MVCCStoreFactoryImplTest.java
Labels: type/improvement

#2646 Auto-throttle read operations
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessor.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ReadEntryProcessorTest.java
  conf/bk_server.conf
Labels: type/improvement

#2636 ISSUE-2640: BP-43: Gradle: Build bookkeeper-server with gradle and run unit tests
  .gitignore
  bookkeeper-common-allocator/build.gradle
  bookkeeper-common/build.gradle
  bookkeeper-http/http-server/build.gradle
  bookkeeper-proto/build.gradle
  bookkeeper-server/build.gradle
  bookkeeper-stats-providers/prometheus-metrics-provider/build.gradle
  bookkeeper-stats/build.gradle
  build.gradle
  circe-checksum/build.gradle
  circe-checksum/src/main/circe/build.gradle
  cpu-affinity/build.gradle
  cpu-affinity/src/main/affinity/build.gradle
  dependencies.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  tools/framework/build.gradle
Labels: area/build

#2656 Upgrade Lombok version
  pom.xml
Labels: area/build

#2661 Fix settings.gradle formatting
  settings.gradle
Labels: area/build

#2662 ISSUE-2640: BP-43: gradle build support for bookkeeper-benchmark and stats module
  bookkeeper-benchmark/build.gradle
  dependencies.gradle
  settings.gradle
  stats/utils/build.gradle
Labels: area/build

#2667 Fix a typo in bookkeeper script
  bin/bookkeeper
Labels: area/bookie, release/4.14.0, type/bug

#2666 ISSUE-2640: BP-43: Build distributions with gradle
  bookkeeper-dist/all/build.gradle
  bookkeeper-dist/bkctl/build.gradle
  bookkeeper-dist/build.gradle
  bookkeeper-dist/server/build.gradle
  bookkeeper-stats-providers/codahale-metrics-provider/build.gradle
  build.gradle
  buildtools/build.gradle
  dependencies.gradle
  settings.gradle
  tools/all/build.gradle
  tools/stream/build.gradle
  version.gradle
Labels: area/build
