Repository apache/bookkeeper, pull requests merged in 2021-08, with the labels that each got.

#2757 Change log level from error to warn in getReadLacResponse
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadLacProcessorV3.java
Labels: area/logging

#2695 [Security] Upgrade libthrift to 0.14.2 to address multiple CVEs
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  dependencies.gradle
  pom.xml
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/acl/ZKAccessControl.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/metadata/BKDLConfig.java
Labels: area/security, type/infra, release/4.15.0

#2762 [Security] Upgrade libthrift to 0.14.2 to address multiple CVEs (backport to branch-4.14)
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  dependencies.gradle
  pom.xml
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/acl/ZKAccessControl.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/metadata/BKDLConfig.java
Labels: area/security, type/infra, release/4.14.2

#2763 Site updates and release note for 4.14.2
  site/_config.yml
  site/docs/4.14.2/admin/autorecovery.md
  site/docs/4.14.2/admin/bookies.md
  site/docs/4.14.2/admin/decomission.md
  site/docs/4.14.2/admin/geo-replication.md
  site/docs/4.14.2/admin/http.md
  site/docs/4.14.2/admin/metrics.md
  site/docs/4.14.2/admin/perf.md
  site/docs/4.14.2/admin/placement.md
  site/docs/4.14.2/admin/upgrade.md
  site/docs/4.14.2/api/distributedlog-api.md
  site/docs/4.14.2/api/ledger-adv-api.md
  site/docs/4.14.2/api/ledger-api.md
  site/docs/4.14.2/api/overview.md
  site/docs/4.14.2/deployment/dcos.md
  site/docs/4.14.2/deployment/kubernetes.md
  site/docs/4.14.2/deployment/manual.md
  site/docs/4.14.2/development/codebase.md
  site/docs/4.14.2/development/protocol.md
  site/docs/4.14.2/getting-started/concepts.md
  site/docs/4.14.2/getting-started/installation.md
  site/docs/4.14.2/getting-started/run-locally.md
  site/docs/4.14.2/overview/overview.md
  site/docs/4.14.2/overview/releaseNotes.md
  site/docs/4.14.2/overview/releaseNotesTemplate.md
  site/docs/4.14.2/reference/cli.md
  site/docs/4.14.2/reference/config.md
  site/docs/4.14.2/reference/metrics.md
  site/docs/4.14.2/security/overview.md
  site/docs/4.14.2/security/sasl.md
  site/docs/4.14.2/security/tls.md
  site/docs/4.14.2/security/zookeeper.md
  site/releases.md
Labels: area/release, release/4.14.2

#2758 state store: getStream: log stream info
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/metadata/RootRangeStoreImpl.java
Labels: type/improvement, area/logging, release/4.15.0

#2761 Issue 2482: Added TCP_USER_TIMEOUT to Epoll channel config
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/conf/NoSystemPropertiesConfigurationTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/conf/SystemPropertiesConfigurationTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/TestPerChannelBookieClient.java
Labels: area/client, type/improvement, release/4.15.0

#2742 Abstract the FileChannel in the JournalChannel
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieFileChannel.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultFileChannel.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultFileChannelProvider.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileChannelProvider.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/JournalChannel.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalForceTest.java
  conf/bk_server.conf
Labels: type/feature, area/bookie, release/4.15.0
