Repository apache/bookkeeper, pull requests merged in 2021-02, with the labels that each got.

#2570 Fix the current site to allow click links in doc
  site/README.md
  site/css/style.sass
Labels: area/website, release/4.13.0, type/bug

#2566 Handling checkpoint corruption in case of bookie crash
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksCheckpointer.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksdbCheckpointTask.java
  stream/statelib/src/test/java/org/apache/bookkeeper/statelib/impl/rocksdb/checkpoint/RocksCheckpointerTest.java
Labels: area/tableservice, release/4.13.0, type/bug

#2562 Limit log output to prevent in case of the large group of the log segments
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/ReadAheadEntryReader.java
Labels: area/tableservice, release/4.13.0, type/bug

#2571 Stream storage endpoint from hostname to return fully-qualified name in Java 11+
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/StorageServer.java
Labels: area/tableservice, release/4.13.0, type/bug

#2573 fix: TableStoreImplTest failed because of NPE in AbstractStateStoreWithJournal initialization (test/mock issue)
  stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/store/MVCCAsyncStoreTestBase.java
Labels: area/tests, release/4.13.0, type/bug

#2568 Issue 2567: Save last revision in rocksdb
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVStore.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCStoreImpl.java
Labels: area/tableservice, release/4.13.0, type/improvement

#2578 Fix: Multiple tests failing in /stream subproject
  stream/statelib/pom.xml
  stream/storage/impl/pom.xml
  stream/storage/impl/src/test/java/org/apache/bookkeeper/stream/storage/impl/store/MVCCStoreFactoryImplTest.java
Labels: area/tableservice, area/tests, release/4.13.0, type/bug

#2575 fix: BKAsyncLogWriter swallows rootcause of the WriteException
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/BKAsyncLogWriter.java
  stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/exceptions/WriteException.java
Labels: area/dlog, area/tableservice, release/4.13.0, type/improvement

#2580 Upgrade protobuf to 3.14.0 (latest)
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Cookie.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerMetadataSerDe.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorElector.java
  pom.xml
Labels: area/bookie, area/client, release/4.13.0, type/improvement

#2589 Fix javadoc for getAllBookies in RegistrationClient interface
  bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/RegistrationClient.java
Labels: area/documentation, release/4.13.0, type/cleanup

#2587 Fix hanging tests tests TestStorageServerClientManagerImpl
  stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/internal/LocationClientImpl.java
  stream/clients/java/base/src/main/java/org/apache/bookkeeper/clients/impl/internal/RootRangeClientImplWithRetries.java
  stream/clients/java/base/src/test/java/org/apache/bookkeeper/clients/grpc/GrpcClientTestBase.java
Labels: area/tableservice, area/tests, release/4.13.0, type/bug

#2595 Fix failing test in /stream
  .github/workflows/stream-tests.yml
  stream/bk-grpc-name-resolver/src/main/java/org/apache/bookkeeper/grpc/resolver/BKRegistrationNameResolver.java
  stream/common/pom.xml
  stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestDistributedLogBase.java
  stream/tests-common/pom.xml
Labels: area/tableservice, area/tests, release/4.13.0, type/bug

#2602 Upgrading dropwizard to 3.2.5
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  pom.xml
Labels: area/stats, release/4.13.0, type/feature

#2603 Fix for licenses problems
  .github/workflows/pr-validation.yml
  bookkeeper-dist/src/assemble/bin-all.xml
  bookkeeper-dist/src/assemble/bin-server.xml
  bookkeeper-dist/src/assemble/bkctl.xml
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  bookkeeper-dist/src/main/resources/deps/checker-qual-3.5.0/LICENSE
  bookkeeper-dist/src/main/resources/deps/google-auth-library-credentials-0.20.0/LICENSE
  bookkeeper-dist/src/main/resources/deps/javax.servlet-api-4.0.0/CDDL+GPL-1.1
  bookkeeper-dist/src/main/resources/deps/jline-2.11/LICENSE
  bookkeeper-dist/src/main/resources/deps/protobuf-3.12.0/LICENSE
  bookkeeper-dist/src/main/resources/deps/protobuf-3.14.0/LICENSE
  dev/check-all-licenses
  dev/check-binary-license
  pom.xml
Labels: area/license, release/4.13.0, type/bug

#2597 Issue 2506: Skip unavailable bookies during verifyLedgerFragment
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookieWatcher.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookieWatcherImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerChecker.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestBookieWatcher.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestLedgerChecker.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/BookieAutoRecoveryTest.java
Labels: area/autorecovery, release/4.13.0, type/feature

#2608 Release script does not work on MacOs Big Sur
  dev/release/000-run-docker.sh
Labels: area/build, release/4.13.0, type/bug

#2609 Fix docker image build - add python3
  docker/Dockerfile
Labels: area/docker, area/release, priority/blocker, release/4.14.0, type/bug

#2621 Issue 2624: Update the NOTICE file to 2021 for copyright.
  NOTICE
Labels: area/license, release/4.13.0, type/cleanup
