Repository apache/bookkeeper, pull requests merged in 2021-05, with the labels that each got.

#2694 [Security] Remove jackson-mapper-asl dependency to resolve multiple CVEs
  bookkeeper-dist/all/pom.xml
  bookkeeper-dist/server/pom.xml
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  pom.xml
  stream/statelib/pom.xml
  stream/storage/impl/pom.xml
Labels: area/security, release/4.14.0, type/bug

#2630 [doc] fix the no striping occurs condition to Qw=E
  site/docs/4.10.0/development/protocol.md
  site/docs/4.11.0/development/protocol.md
  site/docs/4.11.1/development/protocol.md
  site/docs/4.12.0/development/protocol.md
  site/docs/4.12.1/development/protocol.md
  site/docs/4.13.0/development/protocol.md
  site/docs/4.5.0/development/protocol.md
  site/docs/4.5.1/development/protocol.md
  site/docs/4.6.0/development/protocol.md
  site/docs/4.6.1/development/protocol.md
  site/docs/4.6.2/development/protocol.md
  site/docs/4.7.0/development/protocol.md
  site/docs/4.7.1/development/protocol.md
  site/docs/4.7.2/development/protocol.md
  site/docs/4.7.3/development/protocol.md
  site/docs/4.8.0/development/protocol.md
  site/docs/4.8.1/development/protocol.md
  site/docs/4.8.2/development/protocol.md
  site/docs/4.9.0/development/protocol.md
  site/docs/4.9.1/development/protocol.md
  site/docs/4.9.2/development/protocol.md
  site/docs/latest/development/protocol.md
Labels: area/documentation, release/4.14.0, type/bug

#2664 fix: Bookkeeper client throttling logic is based upon entryId instead of ledgerId
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandleAdv.java
Labels: area/client, release/4.14.0, type/bug

#2697 Upgrade Lombok to 1.18.20
  dependencies.gradle
  pom.xml
Labels: area/build, release/4.14.0, type/bug

#2696 [Security] Upgrade Netty to 4.1.63.Final
  bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/impl/ByteBufAllocatorImpl.java
  bookkeeper-dist/all/build.gradle
  bookkeeper-dist/bkctl/build.gradle
  bookkeeper-dist/server/build.gradle
  bookkeeper-dist/src/assemble/bin-all.xml
  bookkeeper-dist/src/assemble/bin-server.xml
  bookkeeper-dist/src/assemble/bkctl.xml
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.aalto-xml.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.base64.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.bouncycastle.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.caliper.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.commons-lang.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.commons-logging.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.compress-lzf.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.dnsinfo.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.harmony.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.hpack.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.hyper-hpack.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.jboss-marshalling.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.jbzip2.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.jctools.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.jfastlz.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.jsr166y.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.jzlib.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.libdivsufsort.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.log4j.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.lz4.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.lzma-java.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.mvn-wrapper.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.nghttp2-hpack.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.protobuf.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.slf4j.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.snappy.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/LICENSE.webbit.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.63.Final/NOTICE.harmony.txt
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/conf/TestBKConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
  dependencies.gradle
  pom.xml
Labels: area/security, release/4.14.0, type/bug

#2707 Read entry error should print lastAddConfirmed in the log
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MdcContextTest.java
Labels: type/improvement

#2401 Allow to bypass journal for writes
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalBypassTest.java
  conf/bk_server.conf
Labels: area/bookie, area/config

#2650 Allow to attach labels to metrics
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperClientStats.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/impl/BookKeeperClientStatsImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestDelayEnsembleChange.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieClientTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
  bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/DataSketchesOpStatsLogger.java
  bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/LongAdderCounter.java
  bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java
  bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusStatsLogger.java
  bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusTextFormatUtil.java
  bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/ScopeContext.java
  bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/SimpleGauge.java
  bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/TestPrometheusMetricsProvider.java
  bookkeeper-stats/src/main/java/org/apache/bookkeeper/stats/StatsLogger.java
Labels: type/improvement

#2658 fix always select the same region set bug for RegionAwareEnsemblePlacementPolicy
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RegionAwareEnsemblePlacementPolicy.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
Labels: type/bug

#2605 Fix logger member not correct、some javadoc problem
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForSingleEntryLog.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexInMemPageMgr.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultBookieAddressResolver.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/ZKRegistrationClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/EventLoopUtil.java
Labels: type/cleanup

#2649 Exception in BK GC with corrupted data files
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
Labels: area/bookie, release/4.14.0, type/bug

#2714 Include gradle files into the source artifact for releases, exclude site2/**
  bookkeeper-dist/src/assemble/src.xml
Labels: area/build, release/4.14.0, type/bug

#2718 fix prometheus metric provider bug and add test to cover label scope …
  bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusTextFormatUtil.java
  bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/TestPrometheusFormatter.java
Labels: area/bookie, release/4.14.0, type/bug

#2719 Update bc tests to include versions up to 4.14.0
  tests/backward-compat/current-server-old-clients/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatOldClients.groovy
  tests/backward-compat/hostname-bookieid/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatUpgradeWithHostnameBookieId.groovy
  tests/backward-compat/upgrade/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatUpgrade.groovy
  tests/docker-images/all-released-versions-image/Dockerfile
Labels: area/tests, release/4.15.0, type/bug

#2724 Site updates and release notes for 4.14.1
  site/_config.yml
  site/docs/4.14.1/admin/autorecovery.md
  site/docs/4.14.1/admin/bookies.md
  site/docs/4.14.1/admin/decomission.md
  site/docs/4.14.1/admin/geo-replication.md
  site/docs/4.14.1/admin/http.md
  site/docs/4.14.1/admin/metrics.md
  site/docs/4.14.1/admin/perf.md
  site/docs/4.14.1/admin/placement.md
  site/docs/4.14.1/admin/upgrade.md
  site/docs/4.14.1/api/distributedlog-api.md
  site/docs/4.14.1/api/ledger-adv-api.md
  site/docs/4.14.1/api/ledger-api.md
  site/docs/4.14.1/api/overview.md
  site/docs/4.14.1/deployment/dcos.md
  site/docs/4.14.1/deployment/kubernetes.md
  site/docs/4.14.1/deployment/manual.md
  site/docs/4.14.1/development/codebase.md
  site/docs/4.14.1/development/protocol.md
  site/docs/4.14.1/getting-started/concepts.md
  site/docs/4.14.1/getting-started/installation.md
  site/docs/4.14.1/getting-started/run-locally.md
  site/docs/4.14.1/overview/overview.md
  site/docs/4.14.1/overview/releaseNotes.md
  site/docs/4.14.1/overview/releaseNotesTemplate.md
  site/docs/4.14.1/reference/cli.md
  site/docs/4.14.1/reference/config.md
  site/docs/4.14.1/reference/metrics.md
  site/docs/4.14.1/security/overview.md
  site/docs/4.14.1/security/sasl.md
  site/docs/4.14.1/security/tls.md
  site/docs/4.14.1/security/zookeeper.md
  site/releases.md
Labels: area/website
