Repository apache/bookkeeper, pull requests merged in 2022-10, with the labels that each got.

#3516 LedgerHandle: do not complete metadata operation on the ZookKeeper/Metadata callback thread
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerCreateOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieWriteLedgerTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeper.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockLedgerHandle.java
Labels: area/client

#3513 LedgerOpenOp: Do not call blocking close() in the callback
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java
Labels: type/bug

#3512 Reduce unnecessary loop in removeIf if map is empty
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMap.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMap.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMap.java
Labels: type/improvement, release/4.15.3

#3500 Add release 4.15.2 release note
  site3/website/src/pages/release-notes.md
Labels: area/release, release/4.15.2

#3518 Bump jackson version to 2.13.4
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  pom.xml
Labels: dependencies, release/4.15.3

#3520 Generate 4.15.2 docs
  site3/website/versioned_docs/version-4.15.2/admin/autorecovery.md
  site3/website/versioned_docs/version-4.15.2/admin/bookies.md
  site3/website/versioned_docs/version-4.15.2/admin/decomission.md
  site3/website/versioned_docs/version-4.15.2/admin/geo-replication.md
  site3/website/versioned_docs/version-4.15.2/admin/http.md
  site3/website/versioned_docs/version-4.15.2/admin/metrics.md
  site3/website/versioned_docs/version-4.15.2/admin/perf.md
  site3/website/versioned_docs/version-4.15.2/admin/placement.md
  site3/website/versioned_docs/version-4.15.2/admin/upgrade.md
  site3/website/versioned_docs/version-4.15.2/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.15.2/api/ledger-adv-api.md
  site3/website/versioned_docs/version-4.15.2/api/ledger-api.md
  site3/website/versioned_docs/version-4.15.2/api/overview.md
  site3/website/versioned_docs/version-4.15.2/deployment/kubernetes.md
  site3/website/versioned_docs/version-4.15.2/deployment/manual.md
  site3/website/versioned_docs/version-4.15.2/development/codebase.md
  site3/website/versioned_docs/version-4.15.2/development/protocol.md
  site3/website/versioned_docs/version-4.15.2/getting-started/concepts.md
  site3/website/versioned_docs/version-4.15.2/getting-started/installation.md
  site3/website/versioned_docs/version-4.15.2/getting-started/run-locally.md
  site3/website/versioned_docs/version-4.15.2/overview/overview.md
  site3/website/versioned_docs/version-4.15.2/reference/cli.md
  site3/website/versioned_docs/version-4.15.2/reference/config.md
  site3/website/versioned_docs/version-4.15.2/security/overview.md
  site3/website/versioned_docs/version-4.15.2/security/sasl.md
  site3/website/versioned_docs/version-4.15.2/security/tls.md
  site3/website/versioned_docs/version-4.15.2/security/zookeeper.md
  site3/website/versioned_sidebars/version-4.15.2-sidebars.json
  site3/website/versions.json
Labels: area/release, release/4.15.2

#3525 Fix byteBuf potential memory leak problem.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
Labels: type/bug, release/4.15.3

#3496 Simplified No network topology script is found default log stack output
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
Labels: type/improvement

#3523 Make the rocksDB configuration compatible with previous versions
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDBTest.java
  bookkeeper-server/src/test/resources/test_entry_location_rocksdb.conf
Labels: release/4.15.3

#3528 Fix memory leak when reading entry but the connection disconnected.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorTest.java
Labels: type/bug, area/bookie, release/4.14.6, release/4.15.3

#3545 Use BlockingQueue.drainTo() in JournalForceWrite thread
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
Labels: type/improvement, release/4.14.6, release/4.15.3

#3505 Rename success with writableResult and update final writableResult about wait writeSet
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/SlowBookieTest.java
Labels: type/bug, release/4.14.6, release/4.15.3

#3503 fix close ledgerAuditorManager repeatedly
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorElector.java
Labels: type/bug, release/4.14.6, release/4.15.3

#3544 Use BlockingQueue.drainTo() in Journal thread
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
Labels: type/improvement, release/4.14.6, release/4.15.3

#3546 Use SingleThreadExecutor for OrderedExecutor and drainTo() tasks into local array
  bookkeeper-common/pom.xml
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedScheduler.java
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/SingleThreadExecutor.java
  bookkeeper-common/src/test/java/org/apache/bookkeeper/common/util/TestSingleThreadExecutor.java
Labels: type/improvement, release/4.14.6, release/4.15.3

#3555 Fix flaky-test testWriteSetWriteableCheck
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/SlowBookieTest.java
Labels: flaky-tests, release/4.15.3

#3540 Update website to record the RocksDB configuration changes
  conf/default_rocksdb.conf.default
  conf/entry_location_rocksdb.conf.default
  conf/ledger_metadata_rocksdb.conf.default
  site3/website/docs/reference/config.md
  site3/website/src/pages/release-notes.md
  site3/website/versioned_docs/version-4.15.2/reference/config.md
Labels: release/4.15.3

#3569 [website][fix]Repair `sequential nodes` address
  site3/website/docs/getting-started/concepts.md
Labels: area/website

#3561 Skipping placementPolicyCheck when ledger replication disabled
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
Labels: type/bug, area/autorecovery, release/4.14.6, release/4.15.3

#3570 Flush time started moved to after lock
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
Labels: type/bug, area/bookie, release/4.15.3

#3522 Change masterKeyCache to dynamic size
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorageNotificationListener.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SortedLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/MockLedgerStorage.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/SyncThreadTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/GcLedgersTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/LedgerManagerTestCase.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMapTest.java
Labels: type/bug

#3575 Single thread executor should not have max capacity by default
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/collections/GrowableMpScArrayConsumerBlockingQueue.java
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/SingleThreadExecutor.java
  bookkeeper-common/src/test/java/org/apache/bookkeeper/common/collections/GrowableArrayBlockingQueueTest.java
  bookkeeper-common/src/test/java/org/apache/bookkeeper/common/util/TestSingleThreadExecutor.java
Labels: type/bug

#3563 Skip replicasCheck when replication disabled
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
Labels: type/bug, area/autorecovery, release/4.14.6, release/4.15.3

#3557 [Branch-4.14] Fix TLS test local port case problem
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieNetworkAddressChangeTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestDelayEnsembleChange.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
Labels: flaky-tests

#3509 Add new api resumeCompaction and suspendCompaction
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SortedLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/ResumeCompactionService.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/SuspendCompactionService.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/MockLedgerStorage.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
  site3/website/docs/admin/http.md
Labels: area/bookie, type/improvement

#3574 [configuration] fix typo in bk_server.conf
  conf/bk_server.conf
Labels: area/config

#3580 Add example for multiple server list in metadataServiceUri configuration
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
  conf/bk_server.conf
Labels: area/config, release/4.14.6, release/4.15.3

#3571 [doc]Fixed incorrect checkstyle configuration prompts
  site3/website/src/pages/community/contributing.md
Labels: area/website

#3576 [test] Fix flaky test testAutoRecoverySessionLoss
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AutoRecoveryMainTest.java
Labels: flaky-tests, release/4.14.6, release/4.15.3

#3579 Upgrade dependencies for CVE-2022-3171 and CVE-2022-42003
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  pom.xml
Labels: dependencies, release/4.14.6, release/4.15.3

#3562 When call openLedgerOp, make the timeout ex is a separate error code
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BKException.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerRecoveryOp.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/api/BookKeeperBuildersOpenLedgerTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/api/BookKeeperBuildersTest.java
Labels: type/bug, area/bookie, release/4.14.6, release/4.15.3

#3589 Issue 3588: write meta to log header before fsync in DirectIO mode
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/LogMetadata.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestMetadata.java
Labels: type/bug, area/bookie

#3590 Fix typo issue when Header.assertFingerPrint throws IOException
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/Header.java
Labels: type/bug, area/bookie

#3587 Add javadoc comments for test classes
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieRecoveryUseIOThreadTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/api/BookKeeperBuildersOpenLedgerTest.java
Labels: area/tests
