Repository apache/bookkeeper, pull requests merged in 2022-11, with the labels that each got.

#3560 Avoid extra buffer to prepend frame size
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufList.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/BookieProtoEncodingTest.java
Labels: type/improvement

#3577 Fix ByteBuf memory leak problem when setExplicitLac
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieImplTest.java
Labels: type/bug, release/4.14.6, release/4.15.3

#3593 Removed the necessity of SafeRunnable
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedScheduler.java
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/SingleThreadSafeScheduledExecutorService.java
  bookkeeper-common/src/test/java/org/apache/bookkeeper/common/concurrent/TestFutureUtils.java
  bookkeeper-common/src/test/java/org/apache/bookkeeper/common/util/TestOrderedExecutorDecorators.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryMemTableWithParallelFlusher.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeper.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ExplicitLacFlushPolicy.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ForceLedgerOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerCreateOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandleAdv.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ReadOnlyLedgerHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/ZKRegistrationClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClientImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ForceLedgerProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/GetBookieInfoProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/GetListOfEntriesOfLedgerProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBaseV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadLacProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteLacProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/OrderedGenericCallback.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeper.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockLedgerHandle.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockBookieClient.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/TestPerChannelBookieClient.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/BKAsyncLogReader.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/ReadAheadEntryReader.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/ZKLogSegmentMetadataStore.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/logsegment/BKLogSegmentEntryReader.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/lock/ZKSessionLock.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/lock/ZKSessionLockFactory.java
Labels: type/improvement

#3595 Allow to use IO uring instead of epoll
  bookkeeper-common/pom.xml
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/EventLoopUtil.java
  pom.xml
Labels: type/improvement

#3597 Optimize ReadResponse for small entry sizes
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
Labels: type/improvement

#3623 [log] Add journal file path that caused failure in multi-journal config
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
Labels: area/bookie, area/logging, release/4.14.6, release/4.15.4

#3622 Fix GetBookieInfo failed event stats
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/GetBookieInfoProcessorV3.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/GetBookieInfoProcessorV3Test.java
Labels: type/bug, release/4.14.6, release/4.15.4

#3489 Issue #3488 Create an EmbeddedSever extracting code from Main class and adding a builder pattern
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/EmbeddedServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/Main.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/server/TestEmbeddedServer.java
Labels: type/improvement

#3632 Include bkperf into bk all package
  bookkeeper-dist/all/pom.xml
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
Labels: dependencies, release/4.14.6, release/4.15.4

#3551 Issue 3550: Fix flaky tests in AuditorReplicasCheckTest
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTest.java
Labels: flaky-tests, release/4.14.6, release/4.15.4

#3615 [branch-4.14] sync pr#3317 Fix maven javadoc generate
  .github/workflows/pr-validation.yml
  bookkeeper-common/pom.xml
  bookkeeper-server/pom.xml
  bookkeeper-server/src/main/java/org/apache/bookkeeper/stats/package-info.java
  bookkeeper-stats-providers/codahale-metrics-provider/src/main/java/org/apache/bookkeeper/stats/package-info.java
  bookkeeper-stats/pom.xml
  bookkeeper-stats/src/main/java/org/apache/bookkeeper/stats/AlertStatsLogger.java
  pom.xml
  site/scripts/javadoc-gen.sh
  stream/distributedlog/pom.xml
Labels: release/4.14.6

#3621 Apply recycle logic during add entry creation but ledger close to LedgerHandleAdv
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandleAdv.java
Labels: type/bug, area/client, release/4.14.6, release/4.15.4

#3640 Upgrade docker image version to fix CVEs
  dev/docker/Dockerfile
  dev/release/Dockerfile
Labels: area/docker, release/4.14.6, release/4.15.4

#3646 Make RocksDB delete entries batch size configurable
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  conf/bk_server.conf
Labels: area/config, release/4.14.6, release/4.15.4

#3647 [Branch-4.14] Add rocksDB read latency and read from storage latency for entry reading
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageStats.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
Labels: area/stats, release/4.14.6

#3649 bookkeeper-daemon script supports restart command
  bin/bookkeeper-daemon.sh
Labels: type/feature, area/tools

#3664 Dont validate CompactionInterval when compaction is disabled
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
Labels: type/improvement

#3661 Check client if closed when complete callback.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java
Labels: type/bug, area/client, release/4.15.4

#3633 Sync dependency version with source version in license
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
Labels: area/license

#3630 Add Http-service to check bookie sanity state
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieSanityService.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
  site3/website/docs/admin/http.md
Labels: area/stats, area/http

#3663 Exit bookkeeper shell correctly even if fails to run for some reason
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/HierarchicalLedgerManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListLedgersCommand.java
Labels: type/bug, area/tools, release/4.15.4

#3662 [fix][server]fix memory leak when operating ledger metadata
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/CleanupLedgerManager.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/CleanupLedgerManagerTest.java
Labels: type/bug, release/4.15.4, release/4.14.7

#3674 [refactor] [server] Refactor ByteBuf release method in InterleavedLedgerStorage
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
Labels: type/bug, area/bookie, release/4.15.4

#3673 [refactor][bookkeeper] Refactor ByteBuf release method in DefaultEntryLogger
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultEntryLogger.java
Labels: type/bug, area/bookie, release/4.15.4

#3675 Enhance simple test
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/SimpleTestCommand.java
  tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/client/SimpleTestCommandTest.java
Labels: type/improvement
