Repository apache/bookkeeper, pull requests merged in 2022-04, with the labels that each got.

#3154 [website] Update current stable version to 4.14.4
  site/_config.yml
  site3/website/docusaurus.config.js
  site3/website/src/components/RecentReleases/index.js
  site3/website/src/pages/releases.md
Labels: area/website, type/cleanup, release/4.15.0

#3167 [branch-4.14] Replace Log4J with Reload4J
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/deps/slf4j-1.7.32/LICENSE.txt
  pom.xml
Labels: area/security, type/improvement, area/logging, release/4.14.5

#2989 Use netty maxDirectMemory instead of DirectMemoryUtils
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/IndexInMemPageMgr.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/DirectMemoryUtils.java
Labels: area/bookie, type/improvement, release/4.16.0

#3164 [website] add CI checks to validate the website
  .github/workflows/website-pr-validation.yml
  site3/README.md
Labels: type/task, area/website, release/4.16.0

#3183 [build] fix master branch broken http-core license check
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  dependencies.gradle
  pom.xml
Labels: type/bug, area/build, release/4.16.0

#2790 only update topology when bookie rack changed
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/TopologyAwareEnsemblePlacementPolicy.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicy.java
Labels: area/bookie, type/improvement, release/4.15.0, release/4.14.5

#3195 Allow running units test on jdk17
  pom.xml
  stream/distributedlog/common/pom.xml
  stream/distributedlog/core/pom.xml
  stream/distributedlog/pom.xml
  stream/pom.xml
  tests/integration-tests-base-groovy/pom.xml
Labels: area/tests

#3187 [website] Make site3 the official website (deploy scripts - master)
  .github/workflows/website-deploy.yaml
  .github/workflows/website-pr-validation.yml
  .github/workflows/website-staging-deploy.yaml
  site3/website/scripts/publish-website.sh
Labels: type/task, area/website, release/4.16.0

#3230 Fix "bookeepeer localbookie"
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
Labels: type/bug, release/4.15.0

#3211 [MINOR] fix logger number not correct
  bookkeeper-common/src/test/java/org/apache/bookkeeper/common/util/TestThreadSelection.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/datainteg/DataIntegrityCookieValidation.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/AuthHandler.java
Labels: area/logging

#3210 [minor] cleanup on InterleavedLedgerStorage
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InMemoryEntryLogMetadataMap.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
Labels: type/cleanup

#3217 Issue 2518:fix error link
  README.md
Labels: area/website

#3232 Bump jetty to 9.4.46.v20220331 to get rid of CVE-2021-34429
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  dependencies.gradle
  pom.xml
Labels: type/task, area/bookie, area/build, dependencies, release/4.15.0

#3240 Fix read empty ledger exception using bookkeeper admin
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperAdminTest.java
Labels: type/bug, area/bookie, area/tools, release/4.15.0

#3213 Format log statements
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ListUnderReplicatedCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ToggleCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/FormatUtil.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/LastMarkCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListActiveLedgersCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListFilesOnDiscCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListLedgersCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadJournalCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLedgerCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLogCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/EndpointInfoCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/InfoCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/ListBookiesCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookies/RecoverCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/LedgerMetaDataCommand.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/SimpleTestCommand.java
Labels: area/bookie, type/cleanup, release/4.15.0

#3227 Fix bookie shell help command exception
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
Labels: area/tools, type/improvement, release/4.15.0

#3201 Correct the method signature within annotations
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookiesListener.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/EnsemblePlacementPolicy.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandleAdv.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/SpeculativeRequestExecutionPolicy.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClient.java
Labels: type/bug, area/bookie, area/documentation, release/4.15.0

#3228 Add get under replicated ledger count
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ListUnderReplicatedCommand.java
  site3/website/docs/reference/cli.md
  tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ListUnderReplicatedCommandTest.java
Labels: type/feature, area/tools, release/4.15.0

#3242 fix some jdk17 test problem
  pom.xml
Labels: dependencies
