Repository apache/bookkeeper, pull requests merged in 2022-12, with the labels that each got.

#3676 Add an argument to decide expose the default JVM metrics
  conf/bk_server.conf
  stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java
Labels: type/improvement

#3687 [refactor][bookkeeper] Refactor ByteBuf release method in tools
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/journal/JournalWriter.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/IncrementTask.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/WriteTask.java
Labels: type/bug, area/bookie, release/4.15.4, release/4.14.7

#3628 Use READ_ENTRY_SCHEDULING_DELAY to stable stickyReadsWithFailures
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieStickyReadsTest.java
Labels: flaky-tests

#3666 Fix RegionAwareEnsemblePlacementPolicy update rack info problem.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RegionAwareEnsemblePlacementPolicy.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
Labels: type/bug, release/4.15.4, release/4.14.7

#3677 Make `jvm_memory_direct_bytes_used` metrics compatible with jdk8.
  stats/bookkeeper-stats-providers/prometheus-metrics-provider/pom.xml
  stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java
  stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/TestPrometheusMetricsProvider.java
Labels: release/4.14.6, release/4.15.4

#3672 [fix][server]fix memory leak when closeRecovered,failed on clearing newEnsemblesFromRecovery
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ReadOnlyLedgerHandle.java
Labels: type/bug, release/4.15.4, release/4.14.7

#3693 [refactor] [server] Refactor ByteBuf release method in module distributedlog-core/distributedlog-protocol
  stream/distributedlog/common/src/test/java/org/apache/distributedlog/io/TestCompressionCodec.java
  stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/EnvelopedRecordSetReader.java
  stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/EnvelopedRecordSetWriter.java
  stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/LogRecord.java
Labels: type/bug, area/bookie, release/4.15.4, release/4.14.7

#3699 [Branch-4.14] Fix cherry-pick #3677 issue
  bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java
Labels: release/4.14.6

#3694 [refactor] [server] Refactor ByteBuf release method in module stream-storage-common/stream-storage-java-kv-client/stream-storage-cli
  stream/clients/java/kv/src/main/java/org/apache/bookkeeper/clients/impl/kv/PByteBufSimpleTableImpl.java
  stream/clients/java/kv/src/main/java/org/apache/bookkeeper/clients/impl/kv/PByteBufTableRangeImpl.java
  stream/common/src/main/java/org/apache/bookkeeper/common/router/AbstractHashRouter.java
  tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/table/DelCommand.java
Labels: type/bug, area/bookie, release/4.15.4, release/4.14.7

#3710 [feature] Added api/v1/bookie/cluster_info REST API
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/ClusterInfoService.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
  site3/website/docs/admin/http.md
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/StorageServer.java
Labels: type/feature, area/bookie, area/http, release/4.16.0

#3713 [FEATURE] Added api/v1/bookie/cluster_info REST API
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/ClusterInfoService.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
  site3/website/docs/admin/http.md
  stream/server/src/main/java/org/apache/bookkeeper/stream/server/StorageServer.java
Labels: release/4.15.4

#3714 [FEATURE] Added api/v1/bookie/cluster_info REST API
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/ClusterInfoService.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
  site/docs/4.11.0/admin/http.md
Labels: release/4.14.7
