Repository apache/bookkeeper, pull requests merged in 2022-01, with the labels that each got.

#2987 Website changes for 4.14.4 release
  site/_config.yml
  site/docs/4.14.4/admin/autorecovery.md
  site/docs/4.14.4/admin/bookies.md
  site/docs/4.14.4/admin/decomission.md
  site/docs/4.14.4/admin/geo-replication.md
  site/docs/4.14.4/admin/http.md
  site/docs/4.14.4/admin/metrics.md
  site/docs/4.14.4/admin/perf.md
  site/docs/4.14.4/admin/placement.md
  site/docs/4.14.4/admin/upgrade.md
  site/docs/4.14.4/api/distributedlog-api.md
  site/docs/4.14.4/api/ledger-adv-api.md
  site/docs/4.14.4/api/ledger-api.md
  site/docs/4.14.4/api/overview.md
  site/docs/4.14.4/deployment/dcos.md
  site/docs/4.14.4/deployment/kubernetes.md
  site/docs/4.14.4/deployment/manual.md
  site/docs/4.14.4/development/codebase.md
  site/docs/4.14.4/development/protocol.md
  site/docs/4.14.4/getting-started/concepts.md
  site/docs/4.14.4/getting-started/installation.md
  site/docs/4.14.4/getting-started/run-locally.md
  site/docs/4.14.4/overview/overview.md
  site/docs/4.14.4/overview/releaseNotes.md
  site/docs/4.14.4/overview/releaseNotesTemplate.md
  site/docs/4.14.4/reference/cli.md
  site/docs/4.14.4/reference/config.md
  site/docs/4.14.4/reference/metrics.md
  site/docs/4.14.4/security/overview.md
  site/docs/4.14.4/security/sasl.md
  site/docs/4.14.4/security/tls.md
  site/docs/4.14.4/security/zookeeper.md
  site/releases.md
Labels: area/website

#2981 Fix region aware placement policy use disk weight not work
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/WeightedRandomSelectionImpl.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
Labels: release/4.15.0

#3011 Auditor should get the LegdgerManagerFactory from the client instance
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
Labels: type/bug
