Repository apache/bookkeeper, pull requests merged in 2022-03, with the labels that each got.

#3027 [ci] Move CI to JDK11
  .github/workflows/bookie-tests.yml
  .github/workflows/client-tests.yml
  .github/workflows/compatibility-check-java11.yml
  .github/workflows/integration-tests.yml
  .github/workflows/pr-validation.yml
  .github/workflows/remaining-tests.yml
  .github/workflows/replication-tests.yml
  .github/workflows/stream-tests.yml
  .github/workflows/tls-tests.yml
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieWriteToJournalTest.java
  tests/docker-images/current-version-image/Dockerfile
  tests/docker-images/current-version-image/image_builder.sh
  tests/docker-images/current-version-image/scripts/install-python-client.sh
  tests/docker-images/images_builder.sh
  tests/docker-images/statestore-image/Dockerfile
Labels: release/4.15.0

#3074 support shrink for ConcurrentLong map or set
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForEntryLogPerLedger.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogMetadata.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/FileInfoBackingCache.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/HandleFactoryImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/WriteCache.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMap.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSet.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMap.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMap.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSet.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMapTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSetTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMapTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMapTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSetTest.java
  metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdLedgerManager.java
  metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdWatchClient.java
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/routing/RangeRoutingTableImpl.java
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/sc/ZkStorageContainerManager.java
  tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadLogMetadataCommandTest.java
Labels: type/improvement

#3071 Fix publish do not include test jar
  build.gradle
Labels: area/build, type/cleanup, release/4.15.0

#3068 Add sizeInBytes interface for ConcurrentLong map and set
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSet.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMap.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMap.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSetTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMapTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMapTest.java
Labels: type/feature, area/bookie, area/stats, release/4.15.0

#3055 check all bookies of writeset are writable
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/SlowBookieTest.java
Labels: type/bug, area/client, release/4.15.0

#2963 Add throttle for rebuild entryMetadataMap
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
Labels: type/feature, area/bookie, release/4.15.0

#3056 change rocksdb init: use OptionsUtil
  bookkeeper-dist/bkctl/build.gradle
  bookkeeper-dist/src/assemble/bkctl.xml
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageFactory.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgersIndexCheckOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgersIndexRebuildOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LocationsIndexRebuildOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/PersistentEntryLogMetadataMap.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageTest.java
  bookkeeper-server/src/test/resources/conf/default_rocksdb.conf
  bookkeeper-server/src/test/resources/conf/entry_location_rocksdb.conf
  bookkeeper-server/src/test/resources/conf/ledger_metadata_rocksdb.conf
  conf/default_rocksdb.conf
  conf/entry_location_rocksdb.conf
  conf/ledger_metadata_rocksdb.conf
Labels: area/bookie, type/improvement, release/4.15.0

#2962 Fix Journal.ForceWriteThread.forceWriteRequests.put deadlock
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookKeeperServerStats.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/stats/JournalStats.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieWriteToJournalTest.java
Labels: type/bug, area/bookie, release/4.15.0

#2799 Add a REST API to get or update bookie readOnly state
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieStateReadOnlyService.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
Labels: type/feature, area/bookie, release/4.15.0, release/4.14.5

#3083 fix a metric error in bookieStats
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
Labels: type/bug, area/bookie, release/4.15.0

#3095 Preparing for the release 4.15
  stream/clients/python/setup.py
Labels: type/task, area/release, release/4.15.0

#3097 bump lombok from 1.18.20 to 1.18.22 to support java17 compile
  dependencies.gradle
Labels: type/task, area/build, release/4.15.0

#3101 Bump testcontainers version to 1.16.3
  dependencies.gradle
Labels: type/task, area/tests, area/build, release/4.15.0

#3114 Gradle build: add mavenLocal() repository
  build.gradle
Labels: area/build, type/improvement, release/4.15.0

#3126 [website] Staging website: images are not visible
  site3/website/docs/api/distributedlog-api.md
  site3/website/docs/deployment/dcos.md
  site3/website/versioned_docs/version-4.10.0/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.10.0/deployment/dcos.md
  site3/website/versioned_docs/version-4.11.1/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.11.1/deployment/dcos.md
  site3/website/versioned_docs/version-4.12.1/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.12.1/deployment/dcos.md
  site3/website/versioned_docs/version-4.13.0/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.13.0/deployment/dcos.md
  site3/website/versioned_docs/version-4.14.4/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.14.4/deployment/dcos.md
  site3/website/versioned_docs/version-4.5.1/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.5.1/deployment/dcos.md
  site3/website/versioned_docs/version-4.6.2/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.6.2/deployment/dcos.md
  site3/website/versioned_docs/version-4.7.3/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.7.3/deployment/dcos.md
  site3/website/versioned_docs/version-4.8.2/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.8.2/deployment/dcos.md
  site3/website/versioned_docs/version-4.9.2/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.9.2/deployment/dcos.md
Labels: type/bug, area/website, release/4.15.0

#3117 Log NoLedgerException at debug level
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadLacProcessorV3.java
Labels: release/4.14.5

#3110 PendingReadOp: Fix ledgerEntryImpl reuse problem
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestParallelRead.java
Labels: type/bug, area/client, release/4.15.0, release/4.14.5

#3143 Upgrade rocksdb to 6.29.4.1
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  dependencies.gradle
  pom.xml
Labels: release/4.15.0

#3140 [security] Upgrade jackson-databind to get rid of CVE-2020-36518
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  build.gradle
  dependencies.gradle
  pom.xml
Labels: release/4.15.0

#3149 BookieAutoRecoveryTest.testEmptyLedgerLosesQuorumEventually fix flaky test, ensure that the Auditor is alive
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AutoRecoveryMain.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/BookieAutoRecoveryTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
Labels: area/tests

#3142 Fix doc code problem.
  site/docs/4.10.0/api/ledger-api.md
  site/docs/4.11.0/api/ledger-api.md
  site/docs/4.11.1/api/ledger-api.md
  site/docs/4.12.0/api/ledger-api.md
  site/docs/4.12.1/api/ledger-api.md
  site/docs/4.13.0/api/ledger-api.md
  site/docs/4.14.0/api/ledger-api.md
  site/docs/4.14.1/api/ledger-api.md
  site/docs/4.14.2/api/ledger-api.md
  site/docs/4.14.3/api/ledger-api.md
  site/docs/4.14.4/api/ledger-api.md
  site/docs/4.5.0/api/ledger-api.md
  site/docs/4.5.1/api/ledger-api.md
  site/docs/4.6.0/api/ledger-api.md
  site/docs/4.6.1/api/ledger-api.md
  site/docs/4.6.2/api/ledger-api.md
  site/docs/4.7.0/api/ledger-api.md
  site/docs/4.7.1/api/ledger-api.md
  site/docs/4.7.2/api/ledger-api.md
  site/docs/4.7.3/api/ledger-api.md
  site/docs/4.8.0/api/ledger-api.md
  site/docs/4.8.1/api/ledger-api.md
  site/docs/4.8.2/api/ledger-api.md
  site/docs/4.9.0/api/ledger-api.md
  site/docs/4.9.1/api/ledger-api.md
  site/docs/4.9.2/api/ledger-api.md
  site/docs/latest/api/ledger-api.md
  site3/website/docs/api/ledger-api.md
  site3/website/versioned_docs/version-4.10.0/api/ledger-api.md
  site3/website/versioned_docs/version-4.11.1/api/ledger-api.md
  site3/website/versioned_docs/version-4.12.1/api/ledger-api.md
  site3/website/versioned_docs/version-4.13.0/api/ledger-api.md
  site3/website/versioned_docs/version-4.14.4/api/ledger-api.md
  site3/website/versioned_docs/version-4.5.1/api/ledger-api.md
  site3/website/versioned_docs/version-4.6.2/api/ledger-api.md
  site3/website/versioned_docs/version-4.7.3/api/ledger-api.md
  site3/website/versioned_docs/version-4.8.2/api/ledger-api.md
  site3/website/versioned_docs/version-4.9.2/api/ledger-api.md
Labels: type/bug, area/documentation, release/4.15.0

#3127 Fix NPE while reordering read-sequence for local-bookie ensemble policy
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LocalBookieEnsemblePlacementPolicy.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestSpeculativeRead.java
Labels: type/bug, area/client, release/4.15.0

#3145 Upgrade ZooKeeper to 3.8.0
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-server/pom.xml
  dependencies.gradle
  pom.xml
  src/owasp-dependency-check-suppressions.xml
  stream/statelib/pom.xml
  stream/storage/impl/pom.xml
Labels: area/metadata, dependencies

#3159 [branch-4.14] Bump Python client version to 4.14.5
  stream/clients/python/setup.py
Labels: type/task, area/release, release/4.14.5

#3152 use mockito.any instead of deprecated mockito.anyObject
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/datainteg/CookieValidationTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/datainteg/DataIntegrityCheckTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/datainteg/EntryCopierTest.java
Labels: area/tests, type/cleanup, release/4.16.0

#3060 Catch onBookieRackChange exception
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/TopologyAwareEnsemblePlacementPolicy.java
Labels: release/4.14.5

#3144 Revert rocksdb compaction on checkpoint to reduce cpu intensive
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
Labels: release/4.14.5

#3161 [website] Update committers page
  site/project/who.md
  site3/website/src/pages/project/who.md
Labels: type/task, area/website, release/4.16.0

#2642 fix region/rack aware placement police replace bookie bug
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RegionAwareEnsemblePlacementPolicy.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/TopologyAwareEnsemblePlacementPolicy.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
Labels: release/4.14.5
