Repository apache/bookkeeper, pull requests merged in 2022-08, with the labels that each got.

#2909 Issue #2908: Replace unsafe NoEntryException with IOException
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultEntryLogger.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerCacheTest.java
Labels: type/bug, area/bookie, release/4.14.6, release/4.15.1

#3438 Revert some unwanted changes in commit 3309
  microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/DigestTypeBenchmark.java
Labels: release/4.16.0, release/4.15.1

#3443 Backport BookieBackpressureForV2Test to branch-4.14
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/BookieBackpressureForV2Test.java
Labels: release/4.14.6

#3444 Add latency stats for entry location index lookup so that possible RocksDB bottleneck can be detected
  bookkeeper-common/src/test/java/org/apache/bookkeeper/test/TestStatsProvider.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndexStats.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndexTest.java
  stats/bookkeeper-stats-api/src/main/java/org/apache/bookkeeper/stats/OpStatsLogger.java
Labels: area/stats

#3448 Fix the tls failed test
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
Labels: area/tests, release/4.15.1

#3450 Fix wrong stats name
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/stats/JournalStats.java
Labels: type/bug, area/stats, release/4.14.6, release/4.15.1

#3453 Confirm content and update .asf.yaml
  .asf.yaml
Labels: type/infra

#3454 Fix group ForceWrite not take effect with forceWriteMarkerSent in while loop of ForceWriteThread
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
Labels: release/4.15.1

#3153 Make netty acceptor threadPool size configurable
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/EventLoopUtil.java
Labels: area/bookie, area/config
