Repository apache/bookkeeper, pull requests merged in 2023-11, with the labels that each got.

#4121 Remove the unused logs in the CleanupLedgerManager.recordPromise
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/CleanupLedgerManager.java
Labels: type/bug, release/4.14.9, release/4.16.4, release/4.15.6

#4125 Make AutoRecovery enable stickyReadS as default.
  conf/bk_server.conf
Labels: area/autorecovery, type/improvement

#4128 Fix no known bookies after reset racks for all BKs
  bookkeeper-server/src/main/java/org/apache/bookkeeper/net/NetworkTopologyImpl.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/net/NetworkTopologyImplTest.java
Labels: type/bug, area/bookie, release/4.16.4, release/4.15.6
