Repository apache/bookkeeper, pull requests merged in 2023-02, with the labels that each got.

#3747 Fix QueueEntry recycle problem.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
Labels: type/bug, area/bookie, release/4.15.4, release/4.14.7

#3768 [Branch-4.14] Revert PR#3653 and make delete entries batch size configurable
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  conf/bk_server.conf
Labels: type/bug, release/4.14.7

#3746 [bookie] Fix memory leak when the Bookie is in read only mode
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java
Labels: type/bug, release/4.15.4, release/4.14.7

#3736 [improve] Optimize masterKeyCache StorageNotificationListener
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorageNotificationListener.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SortedLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/MockLedgerStorage.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/SyncThreadTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/GcLedgersTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/meta/LedgerManagerTestCase.java
Labels: type/improvement

#3655 Issue 3070: Fix issue where checkAllLedgers could get stuck when read throttling is enabled
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
Labels: type/bug, area/autorecovery, release/4.15.4, release/4.14.8

#3603 BookieImpl remove wait until journal quits
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ReadOnlyBookieTest.java
Labels: type/improvement, release/4.15.4

#3728 [fix] Recycle LongPairWrapper after use
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LocationsIndexRebuildOp.java
Labels: type/bug, release/4.15.4, release/4.14.8

#3753 Fix the duplicated JournalQueueStats
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
Labels: area/bookie, area/stats

#3654 Fix numLedgersReplicated metric
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
Labels: type/bug, release/4.15.4

#3683 Not wrap IOException twice form checkpoint
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/WriteCache.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/WriteCacheTest.java
Labels: type/improvement, release/4.15.4, release/4.14.8

#3637 [improvement] Refactor Auditor to simplify the readability
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorBookieCheckTask.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorCheckAllLedgersTask.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTask.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTask.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorStats.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorTask.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorBookieCheckTaskTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorCheckAllLedgersTaskTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTaskTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTaskTest.java
Labels: area/autorecovery, type/improvement

#3781 Fix missing blank in log text
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
Labels: area/logging, release/4.15.4, release/4.14.8

#3725 Fix RegionAwareEnsemblePlacementPolicy.newEnsemble sometimes failed problem.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ZoneawareEnsemblePlacementPolicyImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/net/NetworkTopologyImpl.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicy.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
Labels: type/bug, release/4.15.4, release/4.14.8

#3787 Generate 4.14.7 website docs
  site3/website/docusaurus.config.js
  site3/website/versioned_docs/version-4.14.7/admin/autorecovery.md
  site3/website/versioned_docs/version-4.14.7/admin/bookies.md
  site3/website/versioned_docs/version-4.14.7/admin/decomission.md
  site3/website/versioned_docs/version-4.14.7/admin/geo-replication.md
  site3/website/versioned_docs/version-4.14.7/admin/http.md
  site3/website/versioned_docs/version-4.14.7/admin/metrics.md
  site3/website/versioned_docs/version-4.14.7/admin/perf.md
  site3/website/versioned_docs/version-4.14.7/admin/placement.md
  site3/website/versioned_docs/version-4.14.7/admin/upgrade.md
  site3/website/versioned_docs/version-4.14.7/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.14.7/api/ledger-adv-api.md
  site3/website/versioned_docs/version-4.14.7/api/ledger-api.md
  site3/website/versioned_docs/version-4.14.7/api/overview.md
  site3/website/versioned_docs/version-4.14.7/deployment/kubernetes.md
  site3/website/versioned_docs/version-4.14.7/deployment/manual.md
  site3/website/versioned_docs/version-4.14.7/development/codebase.md
  site3/website/versioned_docs/version-4.14.7/development/protocol.md
  site3/website/versioned_docs/version-4.14.7/getting-started/concepts.md
  site3/website/versioned_docs/version-4.14.7/getting-started/installation.md
  site3/website/versioned_docs/version-4.14.7/getting-started/run-locally.md
  site3/website/versioned_docs/version-4.14.7/overview/overview.md
  site3/website/versioned_docs/version-4.14.7/reference/cli.md
  site3/website/versioned_docs/version-4.14.7/reference/config.md
  site3/website/versioned_docs/version-4.14.7/reference/metrics.md
  site3/website/versioned_docs/version-4.14.7/security/overview.md
  site3/website/versioned_docs/version-4.14.7/security/sasl.md
  site3/website/versioned_docs/version-4.14.7/security/tls.md
  site3/website/versioned_docs/version-4.14.7/security/zookeeper.md
  site3/website/versioned_sidebars/version-4.14.7-sidebars.json
  site3/website/versions.json
Labels: area/website

#3786 DirectWriter only acquire buffer when need write.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectWriter.java
Labels: type/bug, area/directIO

#3791 Change directIO configuration names to avoid confusing
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
  conf/bk_server.conf
Labels: area/directIO

#3784 Made PendingAddOp thread safe
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandleAdv.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClientImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/PendingAddOpTest.java
Labels: type/improvement

#3779 Add logs for ensemble select failed
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
Labels: area/autorecovery, release/4.15.4, release/4.14.8

#3785 Make profile `code-coverage` and `dev-debug` tests using `-Dio.netty.leakDetection.level=paranoid`
  pom.xml
Labels: area/tools

#3795 Upgrade RocksDB version to 7.9.2
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  pom.xml
Labels: dependencies

#3806 Fixed locking of PendingAddOp
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
Labels: type/bug

#3800 Fixed the pivot selection in the group quick-sort
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/ArrayGroupSort.java
  microbenchmarks/src/main/java/org/apache/bookkeeper/bookie/GroupSortBenchmark.java
Labels: type/improvement, release/4.15.5

#3758 Fix ReadEntryProcessor v2 SchedulingDelayStats
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
Labels: area/stats, release/4.14.8, release/4.15.5

#3807 Improvements in ArrayGroupSort
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/ArrayGroupSort.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/WriteCache.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/ArraySortGroupTest.java
  microbenchmarks/src/main/java/org/apache/bookkeeper/bookie/GroupSortBenchmark.java
Labels: type/improvement

#3810 Improved efficiency in DigestManager.verify()
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/CRC32CDigestManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/CRC32DigestManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DirectMemoryCRC32Digest.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DummyDigestManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/MacDigestManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/StandardCRC32Digest.java
  circe-checksum/src/main/java/com/scurrilous/circe/checksum/Crc32cIntChecksum.java
  circe-checksum/src/main/java/com/scurrilous/circe/checksum/IntHash.java
  circe-checksum/src/main/java/com/scurrilous/circe/checksum/Java8IntHash.java
  circe-checksum/src/main/java/com/scurrilous/circe/checksum/Java9IntHash.java
  circe-checksum/src/main/java/com/scurrilous/circe/checksum/JniIntHash.java
  circe-checksum/src/test/java/com/scurrilous/circe/checksum/ChecksumTest.java
  microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManagerBenchmark.java
  microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/DigestTypeBenchmark.java
Labels: type/improvement

#3811 Avoid thread-local state when computing CRCs
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/CRC32CDigestManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/CRC32DigestManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DummyDigestManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/MacDigestManager.java
  microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/DigestTypeBenchmark.java
Labels: type/improvement

#3814 Upgrade lombok to 1.18.26
  pom.xml
Labels: dependencies

#3820 Remove compiling with `-Werror` to support Java 19
  pom.xml
Labels: area/build

#3821 Support update ledger metadata option bk-cli
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/LedgerMetaDataCommand.java
  tools/ledger/src/test/java/org/apache/bookkeeper/tools/cli/commands/client/LedgerMetaDataCommandTest.java
Labels: area/tools

#3822 Fix: bookie-shell ledger-metadata usage with correct param
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
Labels: area/tools

#3823 Fix: typo for ledger-metadata param: restorefromfile
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/client/LedgerMetaDataCommand.java
Labels: area/tools

#3804 fix mailing-lists dead links
  site3/website/src/pages/community/mailing-lists.md
  site3/website/src/pages/community/meeting.md
Labels: area/website
