Repository apache/bookkeeper, pull requests merged in 2023-05, with the labels that each got.

#3933 Generate 4.16.0 website docs
  site3/website/docusaurus.config.js
  site3/website/versioned_docs/version-4.16.0/admin/autorecovery.md
  site3/website/versioned_docs/version-4.16.0/admin/bookies.md
  site3/website/versioned_docs/version-4.16.0/admin/decomission.md
  site3/website/versioned_docs/version-4.16.0/admin/geo-replication.md
  site3/website/versioned_docs/version-4.16.0/admin/http.md
  site3/website/versioned_docs/version-4.16.0/admin/metrics.md
  site3/website/versioned_docs/version-4.16.0/admin/perf.md
  site3/website/versioned_docs/version-4.16.0/admin/placement.md
  site3/website/versioned_docs/version-4.16.0/admin/upgrade.md
  site3/website/versioned_docs/version-4.16.0/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.16.0/api/ledger-adv-api.md
  site3/website/versioned_docs/version-4.16.0/api/ledger-api.md
  site3/website/versioned_docs/version-4.16.0/api/overview.md
  site3/website/versioned_docs/version-4.16.0/deployment/kubernetes.md
  site3/website/versioned_docs/version-4.16.0/deployment/manual.md
  site3/website/versioned_docs/version-4.16.0/development/codebase.md
  site3/website/versioned_docs/version-4.16.0/development/protocol.md
  site3/website/versioned_docs/version-4.16.0/getting-started/concepts.md
  site3/website/versioned_docs/version-4.16.0/getting-started/installation.md
  site3/website/versioned_docs/version-4.16.0/getting-started/run-locally.md
  site3/website/versioned_docs/version-4.16.0/overview/overview.md
  site3/website/versioned_docs/version-4.16.0/reference/cli.md
  site3/website/versioned_docs/version-4.16.0/reference/config.md
  site3/website/versioned_docs/version-4.16.0/security/overview.md
  site3/website/versioned_docs/version-4.16.0/security/sasl.md
  site3/website/versioned_docs/version-4.16.0/security/tls.md
  site3/website/versioned_docs/version-4.16.0/security/zookeeper.md
  site3/website/versioned_sidebars/version-4.16.0-sidebars.json
  site3/website/versions.json
Labels: area/website

#3937 Upgrade jetty version to 9.4.51.v20230217
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  pom.xml
Labels: area/security, release/4.14.8, release/4.15.5, release/4.16.2

#3936 Upgrade docusaurus to 2.4.0
  .github/workflows/website-deploy.yaml
  .github/workflows/website-pr-validation.yml
  site3/website/package.json
  site3/website/yarn.lock
Labels: area/security, release/4.15.5, release/4.16.2

#3927 Fix some metrics generated by prometheus client without type info
  stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusTextFormat.java
  stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/PrometheusTextFormatTest.java
  stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/test/java/org/apache/bookkeeper/stats/prometheus/TestPrometheusFormatter.java
Labels: type/bug, area/stats, release/4.14.8, release/4.15.5, release/4.16.2

#3947 Upgrade rocksDB version to 6.29.4.1
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  pom.xml
Labels: dependencies, release/4.14.8

#3946 When the executor has been shut down, do not schedule task
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
Labels: type/bug, area/autorecovery, release/4.16.2

#3938 drop invalid entryFormat arg from shell command
  bin/bookkeeper
  conf/bkenv.sh
  site3/website/docs/reference/cli.md
  tests/docker-images/statestore-image/bin/bookkeeper
Labels: area/tools, release/4.14.8, release/4.15.5, release/4.16.2

#3901 Fix garbage collection blocked by runtime exception
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
Labels: type/bug, area/bookie, release/4.14.8, release/4.15.5, release/4.16.2

#3955 Fix npe when iterate pendingLedgersUpdates and pendingDeletedLedgers.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
Labels: type/bug, release/4.14.8, release/4.15.5, release/4.16.2

#3959 Avoid compaction to trigger extra flushes DbLedgerStorage
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageTest.java
Labels: type/improvement, release/4.14.8, release/4.15.5, release/4.16.2

#3967 check indexBaseDir specified with ledgerBaseDir
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
Labels: area/bookie, release/4.16.2

#3966 [fix] Clear channel when channelInactive
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
Labels: type/bug, area/client, release/4.14.8, release/4.15.5, release/4.16.2

#3975 Upgrade Netty to 4.1.93.Final
  bookkeeper-dist/src/assemble/bin-all.xml
  bookkeeper-dist/src/assemble/bin-server.xml
  bookkeeper-dist/src/assemble/bkctl.xml
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.aalto-xml.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.base64.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.bouncycastle.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.caliper.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.commons-lang.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.commons-logging.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.compress-lzf.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.dnsinfo.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.harmony.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.hpack.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.hyper-hpack.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.jboss-marshalling.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.jbzip2.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.jctools.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.jfastlz.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.jsr166y.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.jzlib.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.libdivsufsort.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.log4j.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.lz4.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.lzma-java.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.mvn-wrapper.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.nghttp2-hpack.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.protobuf.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.slf4j.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.snappy.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/LICENSE.webbit.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.93.Final/NOTICE.harmony.txt
  pom.xml
Labels: dependencies, release/4.16.2
