Repository apache/bookkeeper, pull requests merged in 2023-10, with the labels that each got.

#4106 Ignore the empty `perRegionPlacement` when RegionAwareEnsemblePlacementPolicy#newEnsemble
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RegionAwareEnsemblePlacementPolicy.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
Labels: area/bookie, type/improvement, release/4.16.4, release/4.15.6

#4112 Upgrade Zookeeper to 3.8.3 to address CVE-2023-44981
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  pom.xml
Labels: dependencies, release/4.16.4

#4072 Update the document of diskUsageWarnThreshold
  conf/bk_server.conf
Labels: area/documentation

#4051 BP62-New API for batched reads
  site3/website/src/pages/bps/BP-62-new-API-for-batched-reads.md
  site3/website/static/img/batch_read.png
  site3/website/static/img/single_read.png
Labels: type/proposal

#4076 Generate 4.14.8 website documents
  site3/website/docusaurus.config.js
  site3/website/versioned_docs/version-4.14.8/admin/autorecovery.md
  site3/website/versioned_docs/version-4.14.8/admin/bookies.md
  site3/website/versioned_docs/version-4.14.8/admin/decomission.md
  site3/website/versioned_docs/version-4.14.8/admin/geo-replication.md
  site3/website/versioned_docs/version-4.14.8/admin/http.md
  site3/website/versioned_docs/version-4.14.8/admin/metrics.md
  site3/website/versioned_docs/version-4.14.8/admin/perf.md
  site3/website/versioned_docs/version-4.14.8/admin/placement.md
  site3/website/versioned_docs/version-4.14.8/admin/upgrade.md
  site3/website/versioned_docs/version-4.14.8/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.14.8/api/ledger-adv-api.md
  site3/website/versioned_docs/version-4.14.8/api/ledger-api.md
  site3/website/versioned_docs/version-4.14.8/api/overview.md
  site3/website/versioned_docs/version-4.14.8/deployment/kubernetes.md
  site3/website/versioned_docs/version-4.14.8/deployment/manual.md
  site3/website/versioned_docs/version-4.14.8/development/codebase.md
  site3/website/versioned_docs/version-4.14.8/development/protocol.md
  site3/website/versioned_docs/version-4.14.8/getting-started/concepts.md
  site3/website/versioned_docs/version-4.14.8/getting-started/installation.md
  site3/website/versioned_docs/version-4.14.8/getting-started/run-locally.md
  site3/website/versioned_docs/version-4.14.8/overview/overview.md
  site3/website/versioned_docs/version-4.14.8/reference/cli.md
  site3/website/versioned_docs/version-4.14.8/reference/config.md
  site3/website/versioned_docs/version-4.14.8/reference/metrics.md
  site3/website/versioned_docs/version-4.14.8/security/overview.md
  site3/website/versioned_docs/version-4.14.8/security/sasl.md
  site3/website/versioned_docs/version-4.14.8/security/tls.md
  site3/website/versioned_docs/version-4.14.8/security/zookeeper.md
  site3/website/versioned_sidebars/version-4.14.8-sidebars.json
  site3/website/versions.json
Labels: area/website

#4077 Fix bug of negative JournalQueueSize
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
Labels: type/bug, area/stats, release/4.16.4

#3915 Upgrade bc-fips to 1.0.2.4 to fix CVE-2022-45146
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  pom.xml
Labels: area/security, release/4.14.9, release/4.16.4, release/4.15.6
