Repository apache/bookkeeper, pull requests merged in 2023-09, with the labels that each got.

#4059 Fix readEntry parameter order
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultEntryLogger.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/DefaultEntryLogTest.java
Labels: type/bug, release/4.16.4

#4070 Optimize bookie decommission check wait interval
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
Labels: area/tools, type/improvement

#4071 Print compaction progress
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
Labels: area/bookie, release/4.15.5, release/4.14.9, release/4.16.4

#4084 Some UTs fail when running under JDK17
  pom.xml
Labels: area/tests

#4039 Fix NoSuchElementException when rereplicate empty ledgers
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestLedgerFragmentReplication.java
Labels: type/bug, area/autorecovery, release/4.15.5, release/4.14.9, release/4.16.4
