Repository apache/bookkeeper, pull requests merged in 2023-12, with the labels that each got.

#4110 issue 4109: Fix Flaky-test: HandleFailuresTest.testHandleFailureBookieNotInWriteSet
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/HandleFailuresTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockBookieClient.java
Labels: flaky-tests, release/4.15.5, release/4.14.9, release/4.16.4

#4078 Make AuditorBookieTest#waitForNewAuditor stronger.
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorBookieTest.java
Labels: flaky-tests, release/4.15.5, release/4.14.9, release/4.16.4

#4144 Use Flaky flag to skip testBookieServerZKSessionExpireBehaviour test
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieZKExpireTest.java
Labels: flaky-tests, release/4.15.5, release/4.14.9, release/4.16.4

#4140 fix calculate checkSum when using Java9IntHash
  circe-checksum/src/main/java/com/scurrilous/circe/checksum/Java9IntHash.java
  circe-checksum/src/test/java/com/scurrilous/circe/checksum/Java9IntHashTest.java
Labels: type/bug, release/4.15.5, release/4.16.4

#4148 Fix the coding-guide page#StatsProvider URL
  site3/website/src/pages/community/coding-guide.md
Labels: area/website

#4138 Add ledgersCount.incrementAndGet in setExplicitLac function
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
Labels: area/stats, release/4.15.5, release/4.14.9, release/4.16.4

#4147 Port the #4058 changes to the branch-4.15
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerUnderreplicationManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/NullMetadataBookieDriver.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationStats.java
Labels: release/4.15.5

#4157 Upgrade Netty to 4.1.104.Final and io_uring to 0.0.24.Final
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  pom.xml
Labels: dependencies

#4162 Fix auditor thread leak problem.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
Labels: type/bug, release/4.14.9, release/4.16.4, release/4.15.6

#4137 Issue 4136: Fix logging configurations are broken in docker image
  docker/scripts/apply-config-from-env.py
  docker/scripts/common.sh
  docker/scripts/init_zookeeper.sh
Labels: area/build, area/docker
