Repository apache/bookkeeper, pull requests merged in 2023-03, with the labels that each got.

#3824 Use JNI directly for posix_fadvise
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-server/pom.xml
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/JournalChannel.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/PageCacheUtil.java
  native-io/src/main/java/org/apache/bookkeeper/common/util/nativeio/NativeIO.java
  native-io/src/main/java/org/apache/bookkeeper/common/util/nativeio/NativeIOImpl.java
  native-io/src/main/java/org/apache/bookkeeper/common/util/nativeio/NativeIOJni.java
  native-io/src/main/native-io-jni/cpp/native_io_jni.c
  pom.xml
  shaded/distributedlog-core-shaded/pom.xml
Labels: type/improvement

#3797 [Branch-4.15] Use ReferenceCountUtil.release() instead of ReferenceCountUtil.safeRelease()
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufList.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/ByteBufListTest.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/logsegment/BKLogSegmentEntryReader.java
Labels: type/bug, release/4.15.4

#3826 Fixed back API of Crc32cIntChecksum
  circe-checksum/src/main/java/com/scurrilous/circe/checksum/Crc32cIntChecksum.java
Labels: type/bug

#3825 Remove callback threadpool for sending add responses
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  conf/bk_server.conf
Labels: type/improvement

#3828 Support build in the aarch64 linux platform
  pom.xml
  src/aarch64_aol.properties
Labels: area/release, release/4.15.4

#3829 Avoid using thread-local WriteSet when possible
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DistributionSchedule.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerChecker.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingWriteLacOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RoundRobinDistributionSchedule.java
Labels: type/improvement

#3836 Fix Spotbugs check failed
  .github/workflows/bk-ci.yml
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/PageCacheUtil.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/LedgerCacheTest.java
  buildtools/src/main/resources/bookkeeper/findbugsExclude.xml
  microbenchmarks/src/main/java/org/apache/bookkeeper/bookie/GroupSortBenchmark.java
  pom.xml
Labels: area/build

#3835 Pass BookieRequestHandler instead of Channel to the request processors
  bookkeeper-server/src/main/java/org/apache/bookkeeper/processor/RequestProcessor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestHandler.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ForceLedgerProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/GetBookieInfoProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/GetListOfEntriesOfLedgerProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/LongPollReadEntryProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBaseV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadLacProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessorV3.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteLacProcessorV3.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ForceLedgerProcessorV3Test.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/GetBookieInfoProcessorV3Test.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/LongPollReadEntryProcessorV3Test.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ReadEntryProcessorTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/TestBookieRequestProcessor.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorV3Test.java
Labels: type/improvement

#3830 Simplified the logic for ForceWriteThread after we introduced queue.drainTo()
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookKeeperServerStats.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/stats/JournalStats.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/OpStatTest.java
Labels: type/improvement

#3789 Add directIO entry logger settings documents
  .github/workflows/website-pr-validation.yml
  site3/website/docs/reference/config.md
Labels: area/documentation, area/directIO

#3796 BP61: revert BP-59 to release ByteBuf using ReferenceCountUtil.release() instead of ReferenceCountUtil.safeRelease()
  bookkeeper-common-allocator/src/test/java/org/apache/bookkeeper/common/allocator/impl/ByteBufAllocatorBuilderTest.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultEntryLogger.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/datainteg/EntryCopierImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/Buffer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectEntryLogger.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectReader.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/LogMetadata.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/LogReaderScan.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClientImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufList.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/CheckpointOnNewLedgersTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestDirectEntryLogger.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/WriteCacheTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/ByteBufListTest.java
  stream/clients/java/kv/src/main/java/org/apache/bookkeeper/clients/impl/kv/PByteBufSimpleTableImpl.java
  stream/clients/java/kv/src/main/java/org/apache/bookkeeper/clients/impl/kv/PByteBufTableRangeImpl.java
  stream/common/src/main/java/org/apache/bookkeeper/common/router/AbstractHashRouter.java
  stream/distributedlog/common/src/test/java/org/apache/distributedlog/io/TestCompressionCodec.java
  stream/distributedlog/core/src/main/java/org/apache/bookkeeper/client/LedgerReader.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/EnvelopedEntry.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/EnvelopedEntryReader.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/EnvelopedEntryWriter.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/logsegment/BKLogSegmentEntryReader.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/tools/DistributedLogTool.java
  stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestEntry.java
  stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/EnvelopedRecordSetReader.java
  stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/EnvelopedRecordSetWriter.java
  stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/LogRecord.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/journal/AbstractStateStoreWithJournal.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/KVUtils.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVAsyncStore.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCRecord.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCRecordCoder.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCStoreImpl.java
  stream/storage/impl/src/main/java/org/apache/bookkeeper/stream/storage/impl/routing/RoutingHeaderProxyInterceptor.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/journal/JournalWriter.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/IncrementTask.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/WriteTask.java
  tools/stream/src/main/java/org/apache/bookkeeper/stream/cli/commands/table/DelCommand.java
Labels: type/bug

#3841 Fix website deploy build failed
  .github/workflows/website-deploy.yaml
Labels: area/build

#3838 Added BatchedArrayBlockingQueue
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/collections/BatchedArrayBlockingQueue.java
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/collections/BatchedBlockingQueue.java
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/collections/BlockingMpscQueue.java
  bookkeeper-common/src/test/java/org/apache/bookkeeper/common/collections/BatchedArrayBlockingQueueTest.java
  microbenchmarks/src/main/java/org/apache/bookkeeper/common/MpScQueueBenchmark.java
Labels: type/improvement

#3652 [improve] Add num not adhering placement ledgers replicated metric for ReplicationWorker
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationStats.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
Labels: area/autorecovery, area/stats

#3837 Group and flush add-responses after journal sync
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/processor/RequestProcessor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestHandler.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/TestBookieRequestProcessor.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/WriteEntryProcessorTest.java
Labels: type/improvement

#3842 Make read entry request recyclable
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ReadEntryProcessor.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/ReadEntryProcessorTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/TestBackwardCompatCMS42.java
Labels: type/improvement

#3855 [Flaky Test] Add timeout for two flaky timeout tests
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/FileInfoBackingCacheTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/HandleFailuresTest.java
Labels: flaky-tests

#3858 Fix bkperf log directory not found
  bin/bkperf
Labels: area/tools

#3850 Bump checkstyle-plugin from 3.1.2 to 3.2.1
  pom.xml
Labels: dependencies

#3857 [Flaky] Fix flaky test in testRaceGuavaEvictAndReleaseBeforeRetain
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/FileInfoBackingCacheTest.java
Labels: flaky-tests

#3859 Fix NPE in BenchThroughputLatency
  bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchThroughputLatency.java
Labels: area/tools

#3862 Update website to 4.15.4
  site3/website/versioned_docs/version-4.15.4/admin/autorecovery.md
  site3/website/versioned_docs/version-4.15.4/admin/bookies.md
  site3/website/versioned_docs/version-4.15.4/admin/decomission.md
  site3/website/versioned_docs/version-4.15.4/admin/geo-replication.md
  site3/website/versioned_docs/version-4.15.4/admin/http.md
  site3/website/versioned_docs/version-4.15.4/admin/metrics.md
  site3/website/versioned_docs/version-4.15.4/admin/perf.md
  site3/website/versioned_docs/version-4.15.4/admin/placement.md
  site3/website/versioned_docs/version-4.15.4/admin/upgrade.md
  site3/website/versioned_docs/version-4.15.4/api/distributedlog-api.md
  site3/website/versioned_docs/version-4.15.4/api/ledger-adv-api.md
  site3/website/versioned_docs/version-4.15.4/api/ledger-api.md
  site3/website/versioned_docs/version-4.15.4/api/overview.md
  site3/website/versioned_docs/version-4.15.4/deployment/kubernetes.md
  site3/website/versioned_docs/version-4.15.4/deployment/manual.md
  site3/website/versioned_docs/version-4.15.4/development/codebase.md
  site3/website/versioned_docs/version-4.15.4/development/protocol.md
  site3/website/versioned_docs/version-4.15.4/getting-started/concepts.md
  site3/website/versioned_docs/version-4.15.4/getting-started/installation.md
  site3/website/versioned_docs/version-4.15.4/getting-started/run-locally.md
  site3/website/versioned_docs/version-4.15.4/overview/overview.md
  site3/website/versioned_docs/version-4.15.4/reference/cli.md
  site3/website/versioned_docs/version-4.15.4/reference/config.md
  site3/website/versioned_docs/version-4.15.4/security/overview.md
  site3/website/versioned_docs/version-4.15.4/security/sasl.md
  site3/website/versioned_docs/version-4.15.4/security/tls.md
  site3/website/versioned_docs/version-4.15.4/security/zookeeper.md
  site3/website/versioned_sidebars/version-4.15.4-sidebars.json
  site3/website/versions.json
Labels: area/website, release/4.15.4

#3860 Modify incorrect rocksDB config level_compaction_dynamic_level_bytes to CFOptions
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDBTest.java
  bookkeeper-server/src/test/resources/conf/entry_location_rocksdb.conf
  bookkeeper-server/src/test/resources/test_entry_location_rocksdb.conf
  conf/entry_location_rocksdb.conf.default
Labels: type/bug, release/4.15.5

#3831 Release note for 4.15.4
  site3/website/src/pages/release-notes.md
Labels: release/4.15.4

#3802 Add trigger entry location index rocksDB compact REST API
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpRouter.java
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/HttpServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/EntryLocationIndex.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/BKHttpServiceProvider.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/TriggerLocationCompactService.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
  site3/website/docs/admin/http.md
Labels: type/feature

#3794 Pick the higher leak detection level between netty and bookkeeper.
  bookkeeper-common-allocator/src/main/java/org/apache/bookkeeper/common/allocator/LeakDetectionPolicy.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/conf/AbstractConfigurationTest.java
Labels: type/improvement

#3631 Add small files check in garbage collection
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/GarbageCollectorThreadTest.java
  conf/bk_server.conf
Labels: type/improvement

#3818 [improvement] Delay all audit task when have a already delayed bookie check task
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorBookieCheckTask.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorCheckAllLedgersTask.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTask.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTask.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorTask.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorCheckAllLedgersTaskTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTaskTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTaskTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
Labels: type/improvement

#3869 [fix][gc] Change order of doGcLedgers and extractMetaFromEntryLogs
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
Labels: area/bookie, type/improvement

#3783 Single buffer for small add requests
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/AuthHandler.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClientImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManager.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ClientUtil.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/LedgerHandleAdapter.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeperTestCase.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ParallelLedgerRecoveryTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ReadLastConfirmedAndEntryOpTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestPendingReadLacOp.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/BookieBackpressureForV2Test.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockBookieClient.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/proto/MockBookies.java
  microbenchmarks/src/main/java/org/apache/bookkeeper/proto/ProtocolBenchmark.java
  microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/DigestManagerBenchmark.java
Labels: type/improvement

#3848 Improve group and flush add-responses after journal sync
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-server/pom.xml
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/processor/RequestProcessor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestHandler.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieServer.java
  pom.xml
Labels: area/bookie, type/improvement

#3878 Add V2 protocol support for BenchReadThroughputLatency
  bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchReadThroughputLatency.java
  bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchThroughputLatency.java
Labels: area/microbenchmarks

#3798 [Branch-4.14] Use ReferenceCountUtil.release() instead of ReferenceCountUtil.safeRelease()
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Bookie.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufList.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/ByteBufListTest.java
  stream/distributedlog/common/src/test/java/org/apache/distributedlog/io/TestCompressionCodec.java
  stream/distributedlog/core/src/main/java/org/apache/bookkeeper/client/LedgerReader.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/EnvelopedEntry.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/EnvelopedEntryReader.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/EnvelopedEntryWriter.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/logsegment/BKLogSegmentEntryReader.java
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/tools/DistributedLogTool.java
  stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestEntry.java
  stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/EnvelopedRecordSetReader.java
  stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/EnvelopedRecordSetWriter.java
  stream/distributedlog/protocol/src/main/java/org/apache/distributedlog/LogRecord.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/journal/AbstractStateStoreWithJournal.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/KVUtils.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/kv/RocksdbKVAsyncStore.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCRecord.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCRecordCoder.java
  stream/statelib/src/main/java/org/apache/bookkeeper/statelib/impl/mvcc/MVCCStoreImpl.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/journal/JournalWriter.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/IncrementTask.java
  tools/perf/src/main/java/org/apache/bookkeeper/tools/perf/table/WriteTask.java
Labels: type/bug, release/4.14.8

#3843 Use BatchedArrayBlockingQueue in Journal
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalForceTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalPageCacheFlushTest.java
Labels: type/improvement

#3884 Fix write entry failed in without writing journal case
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieWriteLedgerTest.java
Labels: type/bug, priority/blocker

#3853 Bump javadoc-plugin from 3.1.1 to 3.2.0
  pom.xml
Labels: dependencies

#3892 [ISSUE 3891] Optimize log4j dependency in Bookkeeper
  bookkeeper-server/pom.xml
  pom.xml
  testtools/pom.xml
Labels: dependencies, release/4.15.5

#3896 Upgrade hadoop version to 3.3.5 to resolve CVE-2019-10202
  pom.xml
Labels: area/security
