Repository apache/bookkeeper, pull requests merged in 2023-01, with the labels that each got.

#3724 Expose registrationClient in DefaultBookieAddressResolver.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultBookieAddressResolver.java
Labels: type/improvement, release/4.15.4, release/4.14.7

#3715 [improve][doc] improve bk_server.conf docs
  conf/bk_server.conf
  site3/website/docs/reference/config.md
Labels: area/documentation, release/4.15.4, release/4.14.7

#3669 Upgrade Netty to 4.1.86.Final
  bookkeeper-dist/src/assemble/bin-all.xml
  bookkeeper-dist/src/assemble/bin-server.xml
  bookkeeper-dist/src/assemble/bkctl.xml
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.aalto-xml.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.base64.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.bouncycastle.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.caliper.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.commons-lang.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.commons-logging.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.compress-lzf.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.dnsinfo.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.harmony.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.hpack.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.hyper-hpack.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.jboss-marshalling.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.jbzip2.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.jctools.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.jfastlz.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.jsr166y.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.jzlib.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.libdivsufsort.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.log4j.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.lz4.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.lzma-java.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.mvn-wrapper.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.nghttp2-hpack.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.protobuf.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.slf4j.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.snappy.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/LICENSE.webbit.txt
  bookkeeper-dist/src/main/resources/deps/netty-4.1.86.Final/NOTICE.harmony.txt
  pom.xml
Labels: dependencies

#3719 BP-60:Change PCBC limitStatsLogging default value to true
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
  site3/website/docs/reference/config.md
Labels: type/improvement

#3573 [docs] update parameter in manual deployment page
  site3/website/docs/deployment/manual.md
Labels: area/website

#3735 CI: move all tests in a single workflow
  .github/workflows/backward-compat-tests.yml
  .github/workflows/bk-ci.yml
  .github/workflows/bookie-tests.yml
  .github/workflows/client-tests.yml
  .github/workflows/compatibility-check-java11.yml
  .github/workflows/compatibility-check-java17.yml
  .github/workflows/compatibility-check-java8.yml
  .github/workflows/integration-tests.yml
  .github/workflows/macos-build.yml
  .github/workflows/owasp-dep-check.yml
  .github/workflows/pr-validation.yml
  .github/workflows/remaining-tests.yml
  .github/workflows/replication-tests.yml
  .github/workflows/stream-tests.yml
  .github/workflows/tls-tests.yml
  .github/workflows/windows-build.yml
Labels: type/improvement
