Repository apache/bookkeeper, pull requests merged in 2023-06, with the labels that each got.

#3979 Fix Journal without flush
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
Labels: release/4.16.2

#3970 Format otel module dependencies
  pom.xml
  stats/bookkeeper-stats-providers/otel-metrics-provider/pom.xml
  stats/bookkeeper-stats-providers/pom.xml
Labels: area/stats

#3983 Fix memory leak of direct memory in direct memory entry logger.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectReader.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectWriter.java
Labels: type/bug, area/directIO, release/4.16.2

#3813 [Bug] Always one orphan ledger is created
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/bk/SimpleLedgerAllocator.java
  stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestBKLogWriteHandler.java
  stream/distributedlog/core/src/test/java/org/apache/distributedlog/TestRollLogSegments.java
Labels: type/bug, area/dlog, release/4.16.2

#3982 Fix arbitrary file upload vulnerability with httpServerEnabled
  bookkeeper-http/vertx-http-server/src/main/java/org/apache/bookkeeper/http/vertx/VertxHttpServer.java
  bookkeeper-http/vertx-http-server/src/test/java/org/apache/bookkeeper/http/vertx/TestVertxHttpServer.java
Labels: type/bug, area/http, release/4.14.8, release/4.15.5, release/4.16.2

#3960 Reduce unnecessary creation of ReplicationEnableCb objects
  bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
Labels: type/improvement, release/4.16.2

#3917 Fix ledger replicated failed blocks bookie decommission process
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragment.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookieWriteLedgerTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/ReplicationTestUtil.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
Labels: type/bug, area/autorecovery, release/4.14.8, release/4.15.5, release/4.16.2

#3985 Unify ByteBufAllocator for the DirectIO component
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/Buffer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/BufferPool.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectCompactionEntryLog.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectEntryLogger.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectReader.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/LogReaderScan.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestBuffer.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestDirectReader.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestDirectWriter.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestMetadata.java
Labels: type/improvement, area/directIO, release/4.16.2

#3989 Change pendingDeletedLedgers as ConcurrentHashSet
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
Labels: type/improvement, release/4.14.8, release/4.15.5, release/4.16.3

#3956 Support skip invalid journal record in replying journal stage
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgersIndexRebuildOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ReadJournalCommand.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieJournalTest.java
Labels: release/4.14.8, release/4.15.5, release/4.16.3

#3994 Make slogger use current class
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectCompactionEntryLog.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectEntryLogger.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/DirectWriter.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/directentrylogger/EntryLogIdsImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/EntryLogTestUtils.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestEntryLogIds.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/directentrylogger/TestTransactionalEntryLogCompactor.java
Labels: type/bug, area/directIO, release/4.16.2

#3993 Upgrade snappy-java to address multiple CVEs
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  pom.xml
Labels: dependencies, release/4.16.2

#3992 Upgrade grpc and protobuf to address CVE-2023-32732
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  metadata-drivers/etcd/pom.xml
  pom.xml
  stream/common/pom.xml
  stream/tests-common/pom.xml
Labels: dependencies, release/4.15.5, release/4.16.2

#3997 Fix issue with binary compatibility with older grpc versions at runtime in the client
  stream/common/src/main/java/org/apache/bookkeeper/common/resolver/ServiceNameResolverProvider.java
Labels: dependencies, release/4.16.2

#3329 Fix data lost when configured multiple ledger directories
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageTest.java
Labels: type/bug, area/bookie, priority/important, release/4.14.8, release/4.15.5

#4001 [Branch-4.16] Downgrade grpc and protobuf to avoid introducing breaking change
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  pom.xml
Labels: release/4.16.2

#3998 Fix trigger GC not work
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/InterleavedLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/LedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/SortedLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/TriggerGCService.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/MockLedgerStorage.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/service/TriggerGCServiceTest.java
Labels: type/bug, release/4.15.5, release/4.16.2
