Repository apache/bookkeeper, pull requests merged in 2024-07, with the labels that each got.

#4458 Update Release Script Instructions and Python Publishing Scripts
  site3/website/src/pages/community/release-guide.md
  stream/clients/python/scripts/publish.sh
Labels: release/4.16.7, release/4.17.2

#4463 [Branch-4.16] [cherry-pick] add dbStorage_readAheadCacheBatchBytesSize properties when read ahead entries
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/TestBookieImpl.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageReadCacheTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/DbLedgerStorageWriteCacheTest.java
  conf/bk_server.conf
Labels: area/bookie

#4439 Correct RackawareEnsemblePlacementPolicyImpl defaultRack when the bookie is not available.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/TopologyAwareEnsemblePlacementPolicy.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicy.java
Labels: type/bug, area/bookie, release/4.15.6, release/4.16.7, release/4.17.2

#4285 Fix the completionObjects leak problem.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
Labels: type/bug, area/client, release/4.15.6, release/4.16.7, release/4.17.2

#4244 Enable ZooKeeper client to establish connection in read-only mode
  bookkeeper-server/src/main/java/org/apache/bookkeeper/zookeeper/ZooKeeperClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/zookeeper/ZooKeeperWatcherBase.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperClientZKSessionExpiry.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ZooKeeperCluster.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/ZooKeeperClusterUtil.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/zookeeper/TestZooKeeperClient.java
Labels: area/bookie, release/4.15.6, release/4.16.7, release/4.17.2

#4476 fix: install netcat-openbsd instead of netcat in test image build
  tests/docker-images/all-released-versions-image/Dockerfile
  tests/docker-images/current-version-image/Dockerfile
  tests/docker-images/statestore-image/Dockerfile
Labels: release/4.16.7, release/4.17.2

#4473 [fix][ci] Fix OWASP Dependency Check download by using NVD API key
  .github/workflows/bk-ci.yml
  .github/workflows/owasp-daily-build.yml
  pom.xml
Labels: release/4.16.7, release/4.17.2

#4468 Fix ReadOnlyLedgerHandle leak issue when checkAllLedgers.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorCheckAllLedgersTask.java
Labels: type/bug, area/autorecovery, release/4.16.7, release/4.17.2

#4469 [Branch-4.16] Fix ReadOnlyLedgerHandle leak issue when checkAllLedgers
  bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/AuditorCheckAllLedgersTask.java
Labels: type/bug, area/autorecovery
