Repository apache/bookkeeper, pull requests merged in 2024-05, with the labels that each got.

#4324 Fix disk weight ensemble infinite loop bug
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRackawareEnsemblePlacementPolicy.java
Labels: type/bug, release/4.14.9, release/4.15.6, release/4.16.6, release/4.17.1

#3849 Bump jetcd from 0.5.0 to 0.7.7
  metadata-drivers/etcd/src/main/java/io/etcd/jetcd/impl/EtcdClientUtils.java
  metadata-drivers/etcd/src/main/java/io/etcd/jetcd/impl/EtcdConnectionManager.java
  metadata-drivers/etcd/src/main/java/io/etcd/jetcd/impl/package-info.java
  metadata-drivers/etcd/src/main/java/org/apache/bookkeeper/metadata/etcd/EtcdWatchClient.java
  pom.xml
  src/owasp-dependency-check-suppressions.xml
Labels: dependencies

#4293 fix: reference counting (retain/release) in PerChannelBookieClient
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/AuthHandler.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieClientImpl.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/ByteStringUtil.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufList.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/ByteBufListTest.java
Labels: release/4.16.6, release/4.17.1

#4383 Remove unused code from ByteBufVisitor
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/ByteBufVisitor.java
Labels: release/4.16.6, release/4.17.1

#4404 Fix TLS stability issues with V2 protocol that caused data corruption
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieNettyServer.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java
Labels: release/4.16.6, release/4.17.1

#4406 Correct Configuration Error in OWASP Dependency Check Plugin Setup
  pom.xml
Labels: release/4.16.6, release/4.17.1

#4400 Override OkHttp Version in Otel to Fix CVE-2023-3635
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  pom.xml
Labels: release/4.16.6, release/4.17.1

#4050 Fix duplicated call zkGetLogSegmentNames in getLogSegmentNames
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/impl/ZKLogSegmentMetadataStore.java
Labels: area/dlog

#4048 Disable annoying logs when segments is empty
  stream/distributedlog/core/src/main/java/org/apache/distributedlog/ReadAheadEntryReader.java
Labels: type/improvement, area/dlog

#4080 Close the RegistrationManager in the finally block in AuditorPlacementPolicyCheckTest.
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTest.java
Labels: area/tests

#4108 Fix the bookkeeper-server-shaded version in ledger-api doc
  site3/website/docs/api/ledger-api.md
  site3/website/versioned_docs/version-4.10.0/api/ledger-api.md
  site3/website/versioned_docs/version-4.11.1/api/ledger-api.md
  site3/website/versioned_docs/version-4.12.1/api/ledger-api.md
  site3/website/versioned_docs/version-4.13.0/api/ledger-api.md
  site3/website/versioned_docs/version-4.14.8/api/ledger-api.md
  site3/website/versioned_docs/version-4.15.5/api/ledger-api.md
  site3/website/versioned_docs/version-4.16.5/api/ledger-api.md
  site3/website/versioned_docs/version-4.17.0/api/ledger-api.md
  site3/website/versioned_docs/version-4.6.2/api/ledger-api.md
  site3/website/versioned_docs/version-4.7.3/api/ledger-api.md
  site3/website/versioned_docs/version-4.8.2/api/ledger-api.md
  site3/website/versioned_docs/version-4.9.2/api/ledger-api.md
Labels: area/website
