Repository apache/bookkeeper, pull requests merged in 2024-04, with the labels that each got.

#4262 Fixed creation of temporary dir in NativeUtils
  circe-checksum/src/main/java/com/scurrilous/circe/utils/NativeUtils.java
  cpu-affinity/src/main/java/org/apache/bookkeeper/common/util/affinity/impl/NativeUtils.java
Labels: type/bug, release/4.16.6

#4266 Use vertx blockingHandlers to run Bookkeeper http handlers which could be blocking
  bookkeeper-http/vertx-http-server/src/main/java/org/apache/bookkeeper/http/vertx/VertxHttpServer.java
Labels: type/bug, release/4.16.6, release/4.17.1

#4283 Fix owasp check failed
  src/owasp-dependency-check-suppressions.xml
Labels: release/4.15.6

#4289 [fix] Fix ByteBuf release/retain in PerChannelBookClient
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieClientTest.java
Labels: type/bug, release/4.16.6, release/4.17.1

#4296 improve: change scheduleAtFixedRate to scheduleWithFixedDelay in GarbageCollectorThread
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
  conf/bk_server.conf
Labels: type/improvement, release/4.14.9, release/4.15.6, release/4.16.6, release/4.17.1

#4066 [fix] Fix ArrayIndexOut0fBoundsException caused by optimistic lock
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMap.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSet.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMap.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMap.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMap.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSet.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMapTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSetTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMapTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongPairHashMapTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashMapTest.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentOpenHashSetTest.java
Labels: type/bug

#3972 Prevent bookie shutdown due to rest api when bookie prohibits readOnlyMode
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieStateManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/StateManager.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/BookieStateReadOnlyService.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/TestHttpService.java
Labels: area/bookie, type/improvement

#3113 Fix the pid occupied check when use bookkeeper-daemon.sh start or stop
  bin/bookkeeper-daemon.sh
Labels: area/bookie
