Repository apache/bookkeeper, pull requests merged in 2024-02, with the labels that each got.

#4139 Enable reorder read sequence for bk client by default
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/MockBookKeeperTestCase.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/ReadLastConfirmedAndEntryOpTest.java
  conf/bk_server.conf
Labels: area/autorecovery, type/improvement, area/config

#4190 [BP-62] Refactor read op, and introduce batchReadOp.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BatchedReadOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ListenerBasedPendingReadOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingReadOp.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ReadOpBase.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestParallelRead.java
Labels: type/feature

#4195 [BP-62] LedgerHandle introduces batch read API.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/ClientInternalConf.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/api/ReadHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BatchedReadEntryProcessor.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestBatchedRead.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestSpeculativeBatchRead.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/test/BookieClientTest.java
Labels: type/feature

#4038 Improve DefaultEntryLogger read performance.
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedReadChannel.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/DefaultEntryLogger.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerBase.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForSingleEntryLog.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLoggerAllocator.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/TransactionalEntryLogCompactor.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/DefaultEntryLogTest.java
Labels: area/bookie, type/improvement

#4209 Fix implicit cast from long to int
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/LedgerMetadataIndex.java
  stats/bookkeeper-stats-providers/codahale-metrics-provider/src/main/java/org/apache/bookkeeper/stats/codahale/FastTimer.java
Labels: area/security

#4211 AutoRecovery supports batch read
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
Labels: type/feature, area/autorecovery

#4210 [BP-62] Add more test for Bookkeeper.
  bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchReadThroughputLatency.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperTest.java
Labels: type/feature

#4184 [improve] fix doc & fix listfilesondisc cmd description
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/bookie/ListFilesOnDiscCommand.java
  docker/README.md
  site3/website/docs/admin/bookies.md
  site3/website/docs/reference/cli.md
  site3/website/src/pages/community/coding-guide.md
Labels: area/documentation
