Repository apache/bookkeeper, pull requests merged in 2024-03, with the labels that each got.

#4219 BenchReadThroughputLatency support config the way of gen ledger path.
  bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchReadThroughputLatency.java
Labels: type/improvement

#4222 Add filename check for unTar
  tests/integration-tests-utils/src/main/java/org/apache/bookkeeper/tests/integration/utils/DockerUtils.java
  tests/integration-tests-utils/src/main/java/org/apache/bookkeeper/tests/integration/utils/MavenClassLoader.java
Labels: type/bug, release/4.15.6, release/4.16.5

#4221 Fix uncontrolled data used in path expression
  bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java
Labels: type/bug, release/4.14.9, release/4.15.6, release/4.16.5

#4223 Fix error stack track may expose to external user
  bookkeeper-http/servlet-http-server/src/main/java/org/apache/bookkeeper/http/servlet/BookieHttpServiceServlet.java
Labels: type/bug, release/4.14.9, release/4.15.6, release/4.16.5

#4224 Upgrade Netty to 4.1.107.Final and io_uring to 0.0.25.Final
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  pom.xml
Labels: dependencies

#4227 [BP-62] Tune the BP-62 doc
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BatchedReadOp.java
  site3/website/src/pages/bps/BP-62-new-API-for-batched-reads.md
Labels: area/documentation

#4220 Fix BenchReadThroughputLatency batch read can't stop problems.
  bookkeeper-benchmark/src/main/java/org/apache/bookkeeper/benchmark/BenchReadThroughputLatency.java
Labels: type/bug

#4208 Issue 2161: set metrics endpoint content-type
  bookkeeper-http/http-server/src/main/java/org/apache/bookkeeper/http/service/HttpServiceResponse.java
  bookkeeper-http/vertx-http-server/src/main/java/org/apache/bookkeeper/http/vertx/VertxAbstractHandler.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/MetricsService.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/server/http/service/MetricsServiceTest.java
Labels: type/bug, release/4.14.9, release/4.15.6, release/4.16.5
