Repository apache/bookkeeper, pull requests merged in 2024-06, with the labels that each got.

#3981 [improve][tests] Backwards compat tests: added new versions, pulsar upgrade cases, read check from old server
  .github/workflows/bk-ci.yml
  tests/backward-compat/upgrade/src/test/groovy/org/apache/bookkeeper/tests/backwardcompat/TestCompatUpgrade.groovy
  tests/docker-images/all-released-versions-image/Dockerfile
  tests/integration-tests-utils/src/main/java/org/apache/bookkeeper/tests/integration/utils/BookKeeperClusterUtils.java
Labels: area/tests

#4361 [ci] Fix apache/pulsar-test-infra/paths-filter action permission in CodeQL workflow
  .github/workflows/codeql.yml
Labels: area/build

#4425 Fix TimedRunnable log NPE
  bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/OrderedExecutor.java
Labels: release/4.16.6, release/4.17.1

#4433 Fix typo-check in CI, run only for pull requests because of security reasons
  .github/workflows/bk-ci.yml
Labels: area/build

#4426 Upgrade to Netty 4.1.111.Final and switch to use grpc-netty-shaded
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  metadata-drivers/etcd/pom.xml
  metadata-drivers/jetcd-core-shaded/pom.xml
  metadata-drivers/pom.xml
  pom.xml
  stream/bk-grpc-name-resolver/src/test/java/org/apache/bookkeeper/grpc/resolver/GrpcChannelsTest.java
  stream/clients/java/base/src/test/java/org/apache/bookkeeper/clients/utils/GrpcChannelsTest.java
  stream/common/pom.xml
  stream/tests-common/pom.xml
Labels: release/4.16.6, release/4.17.1
