Repository apache/bookkeeper, pull requests merged in 2025-04, with the labels that each got.

#4561 Add documentation to bk_server.conf about RocksDB config
  conf/bk_server.conf
Labels: release/4.15.6, release/4.16.7, release/4.17.2

#4555 Fix SST files not being cleaned up in the locations folder
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookKeeperServerStats.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectionStatus.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/stats/GarbageCollectorStats.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/conf/TestServerConfiguration.java
  conf/bk_server.conf
Labels: type/bug, area/bookie, release/4.16.7, release/4.17.2

#4559 Ensure that formatVersion is specified for all RocksDB databases
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
Labels: release/4.15.6, release/4.16.7, release/4.17.2

#4560 Fix and improve locating RocksDB config files
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
  bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java
Labels: release/4.15.6, release/4.16.7, release/4.17.2

#4575 [website]: Update .asf.yaml to add "publish" configuration block
  .asf.yaml
Labels: area/website

#4549 Reduce metadataLock contention in LedgerHandle
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerHandle.java
Labels: release/4.15.6, release/4.16.7, release/4.17.2

#4582 Upgrade Apache Commons libraries to compatible versions
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  pom.xml
Labels: release/4.17.2

#4584 Upgrade Netty to 4.1.119, tcnative to 2.0.70 and io_uring to 0.0.26
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  pom.xml
Labels: area/security, release/4.16.7, release/4.17.2

#4589 Upgrade OpenTelemetry version and align versions using BOMs
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  pom.xml
  stats/bookkeeper-stats-providers/otel-metrics-provider/pom.xml
  stats/bookkeeper-stats-providers/otel-metrics-provider/src/main/java/org/apache/bookkeeper/stats/otel/OtelMetricsProvider.java
Labels: release/4.17.2

#4581 Fix the coredump that occurs when calling KeyValueStorageRocksDB.count after rocksdb has been closed
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDB.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/storage/ldb/KeyValueStorageRocksDBTest.java
Labels: release/4.15.6, release/4.16.7, release/4.17.2

#4591 Upgrade to grpc 1.72.0
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  pom.xml
Labels: release/4.17.2

#4586 Adjust DNS cache expiration in tests to reduce test timeout failures
  .github/workflows/bk-ci.yml
  pom.xml
  stream/distributedlog/common/pom.xml
  stream/distributedlog/core/pom.xml
  stream/distributedlog/pom.xml
  stream/pom.xml
  tests/integration-tests-base-groovy/pom.xml
Labels: release/4.16.7, release/4.17.2

#4597 Upgrade Netty to 4.1.121.Final
  bookkeeper-dist/src/main/resources/LICENSE-all.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/LICENSE-server.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-all.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-bkctl.bin.txt
  bookkeeper-dist/src/main/resources/NOTICE-server.bin.txt
  pom.xml
Labels: dependencies, release/4.16.7, release/4.17.2
