Repository apache/bookkeeper, pull requests merged in 2025-02, with the labels that each got.

#4544 Fix: Garbage collection stuck on corrupt entry log file
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java
Labels: area/bookie

#4535 [cli] Fix: recover command doesn't accept rate limit parameter
  bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/bookie/BookieShellTest.java
Labels: release/4.16.7, release/4.17.2

#4504 [fix] remove in address2Region while bookie left to get correct rack info
  bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RegionAwareEnsemblePlacementPolicy.java
  bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestRegionAwareEnsemblePlacementPolicy.java
Labels: release/4.17.2
